Line 107: [GL1 Error] Invalid bandmode (%d)
Line 158: [GL1 Error] Invalid band (%d)
Line 219: [GL1 Error] Invalid channelType (%d)
Line 267: [GL1 Error] Invalid channelType (%d)
Line 310: [GL1 Error] Invalid Cipher silAlgorithm (%d)
