Line 102: [RF ET][ET S5123 EVT1] RF_Modem_Get_Reg_Mode :: Check RAT - rat (%d)
Line 193: [RF ET][ET S5123 EVT1] TxF_Filter_Set_ET_IN_DATA_SEL CC Info Error : err (0x%x), tx_path info (%d)
Line 230: [RF ET][ET S5123 EVT1] TxF_Filter_Read_ET_IN_DATA_SEL CC Info Error : err (0x%x), tx_path info (%d)
Line 275: [RF ET][ET S5123 EVT1] SW_RESETn1 ET field
Line 348: [RF ET][ET S5123 EVT1] RF_Modem_ET_TxF_Filter_Config_CFR CC Info Error : err (0x%x), tx_path info (%d)
Line 497: [RF ET][ET S5123 EVT1]TxF_Filter_Config_ET_Block CC Info Error : err (0x%x), tx_path info (%d)
Line 564: [RF ET][REG CTRL][DELAY] Fractional delay is not valid! (%d)
Line 569: [RF ET][REG]SET delay %d/%d/%d
Line 592: [RF ET][ET S5123 EVT1] TxF_Filter_Set_Delay CC Info Error : err (0x%x), tx_path info (%d)
Line 659: [RF ET][REG CTRL][DELAY] Fractional delay is not valid! err (0x%x), EFD (%d)
Line 669: [RF ET][REG CTRL][DELAY] Main path bulk delay is not valid! err (0x%x), MBD (0x%x), MBD_I (%d), MBD_Q (%d)
Line 707: [RF ET][ET S5123 EVT1] Fractional delay is not valid! : err (0x%x), tx_path info (%d)
Line 717: [RF ET][REG CTRL][DELAY] Main path bulk delay is not valid! err (0x%x), MBD (0x%x), MBD_I (%d), MBD_Q (%d)
Line 723: [RF ET][ET S5123 EVT1] TxF_Filter_Set_Delay CC Info Error : err (0x%x), tx_path info (%d)
Line 769: [RF ET][ET S5123 EVT1]TxF_Filter_Write_ET_SF_LUT : LUT Number Error(0x%x), LUT NUM (%d)
Line 783: [RF ET] : Negative ET SF data -> Check the ET SF Data : err (0x%x)
Line 812: [RF ET][ET S5123 EVT1]TxF_Filter_Write_ET_SF_LUT : CC Info Error (0x%x), tx_path info (%d)
Line 853: [RF ET][ET S5123 EVT1]TxF_Filter_Config_SF_LUT CC Info Error : err (0x%x), tx_path info (%d)
Line 859: [RF ET][ET S5123 EVT1]TxF_Filter_Config_SF_LUT Config LUT Error : err (0x%x), tx_path info (%d)
Line 889: [RF ET][REG]SET LUT Num %d
Line 902: [RF ET][ET S5123 EVT1]TxF_Filter_Config_DPD_LUT CC Info Error : err (0x%x), tx_path info (%d)
Line 908: [RF ET][ET S5123 EVT1]TxF_Filter_Config_DPD_LUT Config LUT Error : err (0x%x), LUT NUM (%d)
Line 959: [RF ET][ET S5123 EVT1]TxF_Filter_Write_DPD_Value : LUT Number Error(0x%x), LUT NUM (%d)
Line 996: [RF ET][ET S5123 EVT1]TxF_Filter_Write_DPD_Value : CC Info Error (0x%x), tx_path info (%d)
Line 1035: [RF ET][ET S5123 EVT1]TxF_Filter_Write_DPD_Value_All : LUT Number Error(0x%x), LUT CNT (%d)
Line 1052: [RF ET][S355 REG] DPD Data :index(%3d) AM:%4d ,PM:%4d
Line 1080: [RF ET][ET S5123 EVT1]TxF_Filter_Write_DPD_Value_All : CC Info Error (0x%x), tx_path info (%d)
Line 1111: [RF ET][ET S5123 EVT1]TxF_Filter_Set_ET_DAC_IN_Gain CC Info Error : err (0x%x), tx_path info (%d)
Line 1154: [RF ET][ET S5123 EVT1]TxF_Filter_Read_ET_DAC_IN_Gain CC Info Error : err (0x%x), tx_path info (%d)
Line 1199: [RF ET][ET S5123 EVT1]Tx_4G_MOD_GAIN_Set_ET_IFFT_Gain CC Info Error : err (0x%x), tx_path info (%d)
Line 1261: [RF ET][ET S5123 EVT1]Tx_4G_MOD_GAIN_Read_ET_IFFT_Gain CC Info Error : err (0x%x), tx_path info (%d)
Line 1427: [RF ET][ET S5123 EVT1]TxF_Filter_Set_ET_DGC_Gain CC Info Error : err (0x%x), tx_path info (%d)
Line 1468: [RF ET][ET S5123 EVT1]TxF_Filter_Read_ET_DGC_Gain CC Info Error : err (0x%x), tx_path info (%d)
Line 1501: [RF ET][ET S5123 EVT1]TxF_Filter_Set_ET_GainBlock CC Info Error : err (0x%x), tx_path info (%d)
Line 1506: [RF ET][REG]SET gain AMG1:0x%x AMG2:0x%x ENVG1:0x%x ENVG2:0x%x
Line 1552: [RF ET][ET S5123 EVT1]TxF_Filter_Read_ET_GainBlock CC Info Error : err (0x%x), tx_path info (%d)
Line 1593: [RF ET][ET S5123 EVT1]TxF_Filter_Set_ET_LUT_Sel CC Info Error : err (0x%x), tx_path info (%d)
Line 2121: [RF ET][ET S5123 EVT1] Not Allowed TX path [%d]
Line 2294: [RF ET][ET S5123 EVT1]TxF_Filter_Write_DPD_Value_by_Tool : LUT Number Error(0x%x), LUT NUM (%d)
Line 2319: [RF ET][ET S5123 EVT1]TxF_Filter_Write_DPD_Value_by_Tool : CC Info Error (0x%x), tx_path info (%d)
Line 2353: [RF ET][ET S5123 EVT1]TxF_Filter_Write_ET_SF_LUT_by_Tool : LUT Number Error(0x%x), LUT NUM (%d)
Line 2376: [RF ET][ET S5123 EVT1]TxF_Filter_Write_ET_SF_LUT_by_Tool : CC Info Error (0x%x), tx_path info (%d)
Line 2413: [RF ET][ET S5123 EVT1]TxF_Filter_Read_DPD : LUT Number Error(0x%x), LUT NUM (%d)
Line 2439: [RF ET][ET S5123 EVT1]TxF_Filter_Read_DPD : CC Info Error (0x%x), tx_path info (%d)
Line 2474: [RF ET][ET S5123 EVT1]TxF_Filter_Read_SF : LUT Number Error(0x%x), LUT NUM (%d)
Line 2496: [RF ET][ET S5123 EVT1]TxF_Filter_Read_SF : CC Info Error (0x%x), tx_path info (%d)
Line 2537: [ET ERROR][ET S5123 EVT1] Get_Reg_Info_Index :: No Proper Register! reg_type(%d)
Line 2602: [RF ET][Modem Ctrl] ClkGating :: Check RAT - rat (%d)
Line 2606: [RF ET][Modem Ctrl] ClkGating :: rat (%d), on_off(%d)
Line 2642: [RF ET] : RegCtrl_DPD :: Check lut idx - lut_num (%d)
Line 2645: [RF ET][Modem Ctrl] DPD :: rat (%d), lut_num (%d)
Line 2681: [RF ET] : RegCtrl_SF :: Check lut idx - lut_num (%d)
Line 2684: [RF ET][Modem Ctrl] SF :: rat (%d), lut_num (%d)
Line 2750: [RF ET][Modem Ctrl] GainTable :: AMG1 (0x%x), AMG2 (0x%x), ENVG1 (0x%x), ENVG2 (0x%x), ENVOffset (0x%x), reg_mode(0x%x)
Line 2789: [RF ET][Modem Ctrl] LUT SEL :: DPD SEL (0x%X), SFLUT (0x%X), reg_mode (0x%x) -> DPD(0x%x) SF(0x%x)
Line 2829: [RF ET][Modem Ctrl] Delay :: rat (%d), RW_Mode[0/1(Read/Write)] (%d), MB (0x%x), EB (0x%x), EF (%d)
Line 2871: [RF ET][Modem Ctrl] ET DAC :: on_off (%d), et_dac_mode_val (0x%x), et_ctrl (0x%x)
Line 3007: [RF ET][Modem Ctrl] ET_IN_DATA_SEL :: et_in_date_sel (%d)
Line 3045: [RF ET][Modem Ctrl] RegCtrl_ET_DAC_IN_GAIN :: et_dac_in_gain (0x%x)
Line 3085: [RF ET][Modem Ctrl] RegCtrl_IFFT_GAIN :: ifft_slot0 (0x%x), ifft_slot1 (0x%x)
Line 3116: [RF ET][Modem Ctrl] RegCtrl_IFFT_GAIN_SLO :: ifft_gain_tx1 (0x%x), ifft_gain_tx2 (0x%x)
Line 3123: [RF ET][Modem Ctrl] RegCtrl_IFFT_GAIN_SLO :: ifft_gain_tx1 (0x%x), ifft_gain_tx2 (0x%x)
Line 3165: [RF ET][ET S5123 EVT1] Get RFD Path Info Error(0x%x) : rat(%d) tx_path(%d)
Line 3214: [RF ET][Modem Ctrl] RegCtrl_DGC_GAIN :: dgc_gain0 (0x%x), dgc_gain1 (0x%x)
Line 3296: [RF ET] RegCtrl_Config_Main_Path_Block :: error (0x%x)
Line 3354: [RF ET] RegCtrl_Config_ET_Path_Block :: error (0x%x)
Line 3381: [RF ET][Modem Ctrl] Generate_1tone :: tx_path (%d), on_off (%d)
Line 3443: [RF ET] : RegCtrl_Write_DPD_by_Tool :: err (0x%x), Write_DPD_Value_by_Tool Fail
Line 3448: [RF ET] : RegCtrl_Write_DPD_by_Tool :: err (0x%x), Check lut_num (%d)
Line 3451: [RF ET][ET S55AP] RegCtrl_Write_DPD_by_Tool :: rat (%d), lut_num (%d)
Line 3491: [RF ET] : RegCtrl_Write_SF_by_Tool :: err (0x%x), Write_SF_LUT_by_Tool Fail
Line 3496: [RF ET] : RegCtrl_Write_SF_by_Tool :: err (0x%x), Check lut_num (%d)
Line 3499: [RF ET][ET S55AP] RegCtrl_Write_SF_by_Tool :: rat (%d), lut_num (%d)
Line 3532: [RF ET] : RegCtrl_Read_DPD :: Read_DPD Fail
Line 3537: [RF ET] : RegCtrl_Read_DPD :: Read_DPD Fail
Line 3540: [RF ET][ET S55AP] RegCtrl_Read_DPD :: rat (%d), lut_num (%d)
Line 3575: [RF ET] : RegCtrl_Read_SF :: Write_SF_LUT_by_Tool Fail
Line 3580: [RF ET] : RegCtrl_Read_SF :: Check lut_num (%d)
Line 3583: [RF ET][ET S55AP] RegCtrl_Read_SF :: rat (%d), lut_num (%d)
Line 3617: [RF ET] : RegCtrl_DPD :: Check lut cnt - lut_cnt (%d)
Line 3620: [RF ET][Modem Ctrl] DPD :: rat (%d), lut_cnt (%d)
Line 3690: [RF ET][Modem Ctrl] Get_Reg_Addr :: REG TYPE(%d) BASE(0x%x) ADDR(0x%x)
Line 3697: [ET ERROR][ET S5123 EVT1] Get_Reg_Addr :: Out of Range Error : Addr(0x%x) Range(0x%x ~ 0x%x)
Line 3702: [ET ERROR][ET S5123 EVT1] Get_Reg_Addr :: Get reg info index Error
Line 3786: [RF ET][ET S5123 EVT1] RegCtrl_Read_Swap_Status :: ANT SWAP ET PATH 0x%x
