Line 111: Fail to allocate memory!
Line 149: Fail to send message!
Line 154: Fail to build message!
Line 210: [MSG<=] SRM_IMS_START_SVE_RSP
Line 278: [MSG<=] SRM_IMS_STOP_SVE_RSP
Line 346: [MSG<=] SRM_IMS_CHANGE_SVE_RSP
Line 478: [MSG<=] SRM_IMS_OPTION_SET_RSP
Line 572: [MSG<=] SRM_IMS_RECEIVE_DTMF
Line 631: [MSG<=] SRM_IMS_RTP_RX_TIMEOUT_IND
Line 683: [MSG<=] SRM_IMS_RTP_RX_TIMEOUT_CLEAR_IND
Line 735: [MSG<=] SRM_IMS_RTCP_RX_TIMEOUT_IND
Line 787: [MSG<=] SRM_IMS_RTCP_RX_TIMEOUT_CLEAR_IND
Line 858: [MSG<=] SRM_IMS_RTCP_RX_SR_IND
Line 909: [MSG<=] SRM_VCG_CALLESTABLISH_REQ
Line 950: [SESSION] CALLESTABLISH_REQ : bw(%d)freq(%d)br(%u)DTX(%u)
Line 957: [SESSION] CALLESTABLISH_REQ : Chawarerecv(%d)IoMode(%d)SendChannelType(%u)RecvChannelType(%u)
Line 1042: [SESSION] ALTERCODEC_REQ : bw(%d)freq(%d)br(%u)DTX(%u)
Line 1049: [SESSION] ALTERCODEC_REQ : Chawarerecv(%d)IoMode(%d)SendChannelType(%u)RecvChannelType(%u)
Line 1127: [MSG<=] VCG_CALLACTIVATE_IND : cid(%u), freq(%d)
Line 1162: [MSG<=] SRM_VSS_RX_TTY_NTF : utf8Octet(0x%x)
Line 1210: [MSG<=] SRM_IMS_RX_RTT_NTF : channelId(%d), len(%d)
Line 1258: [MSG<=] SRM_SRM_TERMINATE_SESSION_IND : index(%u)
Line 1294: [CALLBACK] socket(%d) event (%d)
Line 1348: [MSG<=] SRM_IMS_FIRST_RTP_IND
Line 1407: [MSG<=] VCG_CALL_QUALITY_INFO_IND
Line 1430: [MSG<=] SRM_SRM_REDUNDANCY_REQ
Line 1462: [MSG<=] SRM_SRM_FRAME_AGGREGATION_REQ
Line 1494: [MSG<=] SRM_SRM_CODEC_MODE_REQ
Line 1526: [MSG<=] Send SRM_SRM_EVS_PRIMARY_RATE_REQ
Line 1558: [MSG<=] SRM_SRM_EVS_BANDWIDTH_REQ to SRM
Line 1590: [MSG<=] Send SRM_SRM_EVS_CHANNEL_AWARE_REQ
Line 1622: [MSG<=] SRM_SRM_EVS_PRIMARY_TO_EVS_AMRWBIO_REQ
Line 1654: [MSG<=] SRM_SRM_EVS_AMRWBIO_TO_EVS_PRIMARY_REQ
Line 1684: [MSG<=] SRM_SRM_UL_CODEC_MODE_IND_REQ
Line 1713: [MSG<=] SRM_SRM_ALTER_CODEC_IND_REQ
Line 1744: [MSG<=] SRM_SRM_CHANGE_BITRATE_REQ
Line 1797: [MSG<=] SRM_IMS_RECOMMENDED_BIT_RATE_QUERY
Line 1860: [SESSION] CHANNELAWARE_REQ : callId(%d) hiLow(%d) offset(%u)
Line 1891: [MSG<=] SRM_IMS_RTP_RX_STATISTICS_IND, event (%d)
Line 1976: [MSG<=] SRM_IMS_VOICE_RTP_QUALITY_IND : channelId(%d)
Line 1982: [RTP_Q] Duration(%d) TX(%d)Lost(%d) RX(%d)Lost(%d)
Line 1986: [RTP_Q] Jitter AVG(%d)MAX(%d) RoundTripTime AVG(%d)
