Line 119: [Proc Rxmode] Operate: PHY_L1C_RXMODE_CHANGE_REQ Rxmode(0x%x)
Line 134: [Proc Rxmode] Rxmode Possible 4rx PHY_L1C_MIB_ACQ_REQ (%d) rxmode_bitmap(%d) isAbove6GHz(%d)
Line 145: [Proc Rxmode] Rxmode Possible 4rx PHY_L1C_DRX_WAKEUP_INIT_REQ (%d) rxmode_bitmap(%d) isAbove6GHz(%d)
Line 164: [Proc Rxmode] SysParam End rxmode_bitmap Mismatch!!! cur_rxmode(%d), Config_rxmode(%d)
Line 167: [Proc Rxmode] Rxmode Possible 4rx PHY_L1C_SYS_PARAM_CHANGE_REQ Pos(%d) NTM_MODE(%d) rxmode_bitmap(%d)
Line 173: [Proc Rxmode] SysParam Cnf done MtmCheck(%d) SyparamCfgdone(%d)
Line 179: [Proc Rxmode] PHY_L1C_TMU_CTRL_IND controlOn(%d) RI(%d)
Line 216: [Proc Rxmode] dataInactivestatus Off DciDeteceted Layer(%d)
Line 263: [Proc Rxmode][DI] dataInactivestatus On Current Rxmode(%x),Rx0_Sinr_ssb(%d),Rx0_Sinr_sch(%d),DlgrantRatio(%d), DLbler(%d)
Line 298: [NR IPC][Proc Rxmode] L1C_PHY_RXMODE_CHANGE_IND, BM_SrcCcForCnfMsg(%d), ind_Rxpath(%d)
Line 319: [NR IPC][Proc Rxmode] L1C_PHY_RXMODE_CHANGE_CNF, BM_SrcCcForCnfMsg(%d), demod_cc(%d)
Line 348: [Proc Rxmode] Configure: Rx ant num(1) -> (%d) 
Line 352: [Proc Rxmode] Configure: Rx ant num(%d)
