Line 241: (F)Error in UpdateSpCfgWithSCellConfig (%d)
Line 286: (F)Error in UpdateTtiCfgWithSCellConfig (%d)
Line 324: [Proc Rxmode] Configure: Rx ant num(1) -> (%d) 
Line 373: [NR_CA_PROC] UpdateTtiCfgWithSCellActDeact(%d) frontCcIdx(%d) rfdIdx(%d/%d) ant_num(%d) scs_ssb(%d) cell_id(%d)
Line 671: (F)Error in UpdateTxCfgWithSCellConfig (%d)
Line 713: (F)Error in UpdateDcCfgWithSCellConfig (%d)
Line 755: (F)Error in UpdateDfCfgWithSCellConfig (%d)
Line 797: (F)Error in UpdateDsCfgWithSCellConfig (%d)
Line 839: (F)Error in UpdateCsiCfgWithSCellConfig (%d)
Line 892: UpdateSpCfgWithSCellConfig : freqRange(%d)
Line 1007: (F)Error in UpdateSpCfgWithSCellConfig (%d)
Line 1127: (F)Error in UpdateIntraCfgWithSCellConfig (%d)
Line 1164: (F)Error in UpdateIntraCfgWithSCellConfigForPcell (%d)
Line 1186: [PROC][CA] ERROR: NumofScell(%d)
Line 1211: [PROC][CA] CaScellInfo: NumofScell(%d)/ScellIndex(%d)/CcIndex(%d)/CcIdxBitMap(0x%X)
Line 1228: (I)Skip DB update: m_CcIdx(%d) MyScellIndex(%d)
Line 1234: (I)Skip DB update: MyScellIndex(%d) MyArrayIndex(%d)
Line 1351: (F)ERROR in Update_CaCommonConfigInfo: state(%d)
Line 1382: (F)ERROR in Update_CaDlConfigInfo: state(%d)
Line 1413: (F)ERROR in Update_CaUlConfigInfo: state(%d)
Line 1441: (F)ERROR in Cmd(%d)
Line 1473: (F)ERROR in NumOfTotalDlActCC(%d)
Line 1477: (F)ERROR in Cmd(%d)
Line 1716: [PROC][CA] CaCfgState(%d)
Line 1739: (F)ERROR in Control_CaCfgState: state(%d)
Line 1888: [NR IPC] L2_PHY_SCELL_DEACT_IND , BM_SrcCcForCnfMsg(%d) m_CcIdx(%d) ServingCellId(%d)
Line 1898: (F)Error in SendScellDeactInd: m_CcIdx(%d)
Line 1964: [PROC][CA] CaActDeactState(%d)
Line 1993: (F)ERROR in CaActDeActState: state(%d)
Line 2086: (F)Error in Update_ScellStatus: m_CcIdx(%d)
Line 2095: (F)Error in Update_ScellStatus: Cmd(%d)
Line 2123: PHY_PHY_SCELL_STATUS_UPDATE_IND m_CcIdx(%d), ActDeact(%d), NrActFlag(0x%x)
Line 2138: [NR IPC] PHY_PHY_SCELL_STATUS_UPDATE_IND, BM_SrcCc(0x%X), BM_DstCc(0x%X)
Line 2309: (F)Error in Config: m_CcOffsetIdx(%d)
Line 2373: (F)Error in Set_ScellDeactTimerTarget: timer(%d)
Line 2558: [NR IPC] L1C_PHY_CELLGROUP_SCELL_CONFIG_CNF, BM_SrcCcForCnfMsg(%d)
Line 2592: [NR IPC] L1C_PHY_SCELL_ACTDEACT_CNF (ACT), BM_SrcCcForCnfMsg(%d), ipc(%d)
Line 2596: [NR IPC] L1C_PHY_SCELL_ACTDEACT_CNF (DEACT), BM_SrcCcForCnfMsg(%d), ipc(%d)
