Line 516: ###[NR_RXFILTER] InitRxFilter: mode(%d)
Line 591: ###[NR_RXFILTER] ConfigRxFilter: rf(%d), mxr(%d), rtg(%d), pgc(%d), mode(%d), bw(%d)
Line 696: ###[NR_RXFILTER] CordicRxFilter: Cordic is enabled
Line 791: ###[NR_RXFILTER] Unknown IQC mode(%d)
Line 796: ###[NR_RXFILTER] ConfigIQC: iqc(%d), mode(%d)
Line 843: ###[NR_RXFILTER] GetIqcCoeff(%d).prx: TAP(%d), I(%x), Q(%x)
Line 859: ###[NR_RXFILTER] GetIqcCoeff(%d).drx: TAP(%d), I(%x), Q(%x)
Line 903: ###[NR_RXFILTER] SetIqcCoeff(%d).prx: TAP(%d), I(%x), Q(%x)
Line 915: ###[NR_RXFILTER] SetIqcCoeff(%d).drx: TAP(%d), I(%x), Q(%x)
Line 998: ###[NR_RXFILTER][WARNIING] ConfigDCR:: Abnormal mode(%d)
Line 1003: ###[NR_RXFILTER] ConfigDCR: dcr(%d), mode(%d)
Line 1460: ###[NR_RXFILTER] Not supported CC path(%d) for D2D
Line 1485: ###[NR_RXFILTER] Not supported CC path(%d) for D2D
Line 1532: ###[NR_RXFILTER] Unknown AGC mode(%d)
Line 1553: ###[NR_RXFILTER] ConfigAGC: rf(%d), dcr(%d), mxr(%d), bw(%d), mode(%d)
Line 1581: ###[NR_RXFILTER] GetAgcGainIdx: mxr(%d), agc_gain(%d, %d)
Line 1609: ###[NR_RXFILTER] GetAgcTdPwr: mxr(%d), td_pwr(%d, %d)
Line 1757: ###[NR_RXFILTER] ConfigSyncDCF: mxr(%d), mode(%d), bw(%d), scs(%d), sampling_mode(%x), RXF_SYNC_4G= 0x%08x, RXF_SYNC_FREQ_VALUE[0]=%d
Line 1763: ###[NR_RXFILTER] ConfigSyncDCF(Disable): mode(%d)
Line 1815: ###[NR_RXFILTER] ConfigSrrcf: mxr(%d), enable(%d), bw(%d)
Line 1880: ###[NR_RXFILTER] ConfigDvga: mxr(%d), enable(%d), bw(%d)
Line 1932: ###[NR_RXFILTER] ConfigGainSplitter: dcr(%d), mode(%x)
Line 1965: ###[NR_RXFILTER] SetModeSetChange: dcr_sel(%d) dif_out_data_sel(0x%X)
Line 1994: ###[NR_RXFILTER] SetModeSetChange: dcr_sel(%d), mmdcr_prx(%d), mmdcr_drx(%d), RFM_VALID(0x%X)
Line 2013: ###[NR_RXFILTER] SetModeSetChange: dcr_sel(%d), mmdcr_prx(%d), mmdcr_drx(%d), RFM_VALID(0x%X)
Line 2020: ###[NR_RXFILTER] SetModeSetChange: dcr_sel(%d), ratsamplingchanged(%d)
Line 2056: ###[NR_RXFILTER] SetRxFilterOutput: out(%d), mxr(%d, %d)
Line 2161: ###[NR_RXFILTER] SetRxFilterSysTime: rf(%d), dcr(%d), mxr(%d), rtg(%d)
Line 2331: ###[NR_RXFILTER] GetMxrSelList: rf(%d), mxr(%d, %d), rx_mode(%d)
Line 2407: ###[NR_RXFILTER] SetAgcAntInput: dcr(%d), mxr(%d), RXF_AGC_ANT_INPUT(%x)
Line 2550: ###[NR_RXFILTER] SetRxFilterMxr: rf(%d), dcr(%d), mxr(%d), mode(%x), bw(%d), mixer_next(%8x)
Line 2629: ###[NR_RXFILTER] SetPgcRamSel: dcr(%d), pgc(%d), ram_sel(%d, %d)
Line 2712: ###[NR_RXFILTER] SetPgcRamTable: Invalid RAM index(%d)
Line 2783: ###[NR_RXFILTER] SetPgcRamTable: RAM%d[%d] = WR(0x%x, 0x%x), RD(0x%x, 0x%x)
Line 2796: ###[NR_RXFILTER] SetPgcRamTable: pgc(%d), addr(0x%06x), band(%d -> %d), ram(%d, %d), size(%d)
Line 2846: ###[NR_RXFILTER] SetRxIqSwap: rf(%d), enable(%d)
Line 3001: ###[NR_RXFILTER] SetRxFilterInput: rf(%d), dcr(%d), mode(%x), bw(%d)
Line 3039: ###[NR_RXFILTER] GetRxDelay, cc: %d, bw: %d, dly: %d, srchBw %d, delay %d
Line 3078: ###[NR_RXFILTER] SetExtLnaModeOvr: rf(%d), dcr(%d), ov(%d), wr(%d)
Line 3132: ###[NR_RXFILTER] ChangeRxMode for FBRX(CC%d) mode(%x)
Line 3161: ###[NR_RXFILTER] ChangeRxMode: rf(%d), mxr(%d), rtg(%d), pgc(%d), mode(%x), bw(%d)
Line 3204: ###[NR_RXFILTER] ChangeDlBw: rf(%d), dcr(%d), mxr(%d), rtg(%d), pgc(%d), mode(%x), bw(%d)
Line 3246: ###[NR_RXFILTER] SetAdcReset: dcr(%d), adc(%d)
Line 3296: ###[NR_RXFILTER] SetExtLnaHysteresis: rf(%d), dcr(%d), hys[0](%d), hys[1](%d), hys[2](%d)
Line 3390: ###[NR_RXFILTER] SetExtLnaMode: rf(%d), dcr(%d), mode(%d)
Line 3397: ###[NR_RXFILTER] SetExtLnaMode: hys[0](%d), hys[1](%d), hys[2](%d), offset[0](%d), offset[1](%d), offset[2](%d)
Line 3491: ###[NR_RXFILTER] SetAgcHysteresis
Line 3538: ###[NR_RXFILTER] GetRxDmixerFreq: mxr(%d), freq(%d, %d), bw(%d)
Line 3599: ###[NR_RXFILTER] SetRxDmixerFreq: mxr(%d), freq(%d, %d), bw(%d, %d)
Line 3664: ###[NR_RXFILTER] SetAgcGainIdx: mxr(%d), gain(%d, %d), ovr(%d, %d)
Line 3951: ###[NR_RXFILTER] AGC: MXR%d, PWR_DB(%d), GAIN(%d, %05d, %2d), PGC(0x%08x, 0x%08x)
Line 3975: ###[NR_RXFILTER] DCR: ANT%d IQ(%d, %d) PWR_DB(%d)
Line 3984: ###[NR_RXFILTER] DCR: RF(%d), OPERATION_SET(0x%x), RFD_ACCUM(0x%x, 0x%x), RFD_ACCUM_VALUE(0x%x, 0x%x), RFD_DB_PWR(%04x)
Line 3985: ###[NR_RXFILTER] SYSTIME: SYSTEM_INFO(0x%x), PATH_ENABLE(0x%x, 0x%x), ULDL_CFG(0x%x, 0x%x)
Line 3986: ###[NR_RXFILTER] RFIC: CHIP_ID(0x%x), RX_LATCH_CTRL(0x%x), RX_UPDATE(0x%x), RX_CONFIG(0x%x, 0x%x), RX_GAIN_CTRL(0x%x, 0x%x)
Line 4013: ###[NR_RXFILTER] IQC: ANT%d TAP%d COEF(%d, %d) PWR(%d)
Line 4022: ###[NR_RXFILTER] IQC: OPERATION_SET[%d](0x%x), COEF_OV[%x](0x%x, 0x%x)
Line 4039: ###[NR_RXFILTER] DMIXER: MXR%d, AFC(%d, %d), SLO(%d, %d)
Line 4067: ###[NR_RXFILTER] mmAGC: MXR%d, PWR_DB(%d), GAIN(%d, %05d, %2d), HYS(0x%08x), PGC(0x%08x)
Line 4090: ###[NR_RXFILTER][RFM] mmDCR: ANT%d P%d I/Q(%d, %d) PWR(%d)
Line 4110: ###[NR_RXFILTER][RFM] mmIQC: ANT%d W0 %d A0 %d
Line 4126: ###[NR_RXFILTER][RFM] mmDMIXER: MXR%d, AFC(%d, %d), SLO(%d, %d)
Line 4317: ###[NR_RXFILTER] SetFbRx: RFD_MPLL_CLK_SEL_CC%d (%X)
Line 4327: ###[NR_RXFILTER] SetFbRx: RFD_FBRX_SAMPLING_MODE(0x%X), FBRX_SAMPLING_MODE(0x%X)
Line 4373: ###[NR_RXFILTER] SetFbRx: RFD_FBRX_INPUT_SEL(0x%X), RXF_MIXER_NEXT(0x%X)
Line 4383: ###[NR_RXFILTER] SetFbRx: rf(%d), dcr(%d), mode(%d), bw(%d)
Line 4424: ###[NR_RXFILTER] SetRxFilterMmInput: MIX_RAT_SAMPLING_MODE(0x%x)
Line 4431: ###[NR_RXFILTER] SetRxFilterMmInput: MIX_RAT_SAMPLING_MODE_DIV_EN(0x%x)
Line 4438: ###[NR_RXFILTER] SetRxFilterMmInput: MIXER_INPUT_SEL(0x%x)
Line 4468: ###[NR_RXFILTER] SetRxFilterMmInput: dcr(%d), mode(%x), bw(%d)
Line 4533: ###[NR_RXFILTER] SetRxFilterMmMxr: dcr_sel(%d), MIXER_NEXT(0x%x)
Line 4534: ###[NR_RXFILTER] SetRxFilterMmMxr: mxr_sel(%d), MM_MIXER_NEXT(0x%x)
Line 4544: ###[NR_RXFILTER] SetRxFilterMmMxr: dcr(%d), mxr(%d), mode(%x), bw(%d)
Line 4591: ###[NR_RXFILTER] ConfigMmIQC: Unknown IQC mode(%d)
Line 4597: ###[NR_RXFILTER] ConfigMmIQC: iqc(%d), mode(%d)
Line 4637: ###[NR_RXFILTER] ConfigMmDCR: Invalid bw(%d)
Line 4660: ###[NR_RXFILTER] ConfigMmDCR: Unknown DCR mode(%d)
Line 4666: ###[NR_RXFILTER] ConfigMmDCR: dcr(%d), mode(%d)
Line 4856: ###[NR_RXFILTER] ConfigMmAGC: Invalid bw(%d)
Line 4912: ###[NR_RXFILTER] ConfigMmAGC: Unknown AGC mode(%d)
Line 4923: ###[NR_RXFILTER] ConfigMmAGC: dcr(0x%X), mxr(%d), bw(%d), mode(%d)
Line 4982: ###[NR_RXFILTER] SetRxFilterMmSysTime: dcr(%d), mxr(%d), rtg(%d)
