Line 251: [HALRXF] SetMaxAnaDifPathNum: Digital Path(%d), Analog Path(%d)
Line 293: [HALRXF] %s: Wrong %s(%d)
Line 294: [HALRXF] %s: Wrong %s(%d)
Line 295: [HALRXF] %s: Wrong %s(%d)
Line 314: [HALRXF] SwapIQ: RFD_DCR_DATA_SEL_IQ_SEL(0x%X)
Line 328: [HALRXF] SwapIQ: rat(%d), dcr(%d), enable(%d)
Line 353: [HALRXF] %s: Wrong %s(%d)
Line 354: [HALRXF] %s: Wrong %s(%d)
Line 400: [HALRXF] %s: Wrong %s(%d)
Line 439: [HALRXF] InitRatSamplingMode: Wrong Rat(%d)
Line 521: [HALRXF] SetRatSamplingMode: rat(%d), max_cc(%d), max_rfPath(%d)
Line 550: [HALRXF] %s: Wrong %s(%d)
Line 559: [HALRXF] %s: Wrong %s(%d)
Line 595: [HALRXF] %s: Wrong %s(%d)
Line 629: [HALRXF] GetRatSamplingMode: Wrong Rat(%d)
Line 645: [HALRXF] GetRatSamplingMode: rat(%d), bw(%d), RatSamplingMode(0x%X)
Line 676: [HALRXF] %s: Wrong %s(%d)
Line 677: [HALRXF] %s: Wrong %s(%d)
Line 678: [HALRXF] %s: Wrong %s(%d)
Line 764: [HALRXF] SetRatSamplingMode: RXF_RAT_SAMPLING_MODE[%d](0x%X), RFD_RXF_RAT_[%d](0x%X) ?= rfd_ccinfo(0x%X)
Line 765: [HALRXF] SetRatSamplingMode: rat(%d), dcr_sel(%d), rx_mode(%d)
Line 808: [HALRXF] %s: Wrong %s(%d)
Line 809: [HALRXF] %s: Wrong %s(%d)
Line 810: [HALRXF] %s: Wrong %s(%d)
Line 858: [HALRXF] SetMixRatSamplingMode: Wrong Rat(%d)
Line 865: [HALRXF] SetMixRatSamplingMode: RXF_MIX_RAT_SAMPLING_MODE[%d](0x%X)
Line 866: [HALRXF] SetMixRatSamplingMode: rat(%d), mxr_sel(%d), rx_mode(%d)
Line 889: [HALRXF] %s: Wrong %s(%d)
Line 1114: [HALRXF] InitRxFilter: Wrong Rat(%d)
Line 1124: [HALRXF] InitRxFilter: Rat(%d)
Line 1150: [HALRXF] %s: Wrong %s(%d)
Line 1366: [HALRXF] CLOCK[INIT]: Wrong Rat(%d)
Line 1377: [HALRXF] CLOCK[INIT]: rat(%d)
Line 1403: [HALRXF] %s: Wrong %s(%d)
Line 1529: [HALRXF] OPERATION[INIT]: Wrong Rat(%d)
Line 1540: [HALRXF] OPERATION[INIT]: rat(%d)
Line 1566: [HALRXF] %s: Wrong %s(%d)
Line 1678: [HALRXF] DVGA[INIT]: Wrong Rat(%d)
Line 1689: [HALRXF] DVGA[INIT]: rat(%d)
Line 1716: [HALRXF] %s: Wrong %s(%d)
Line 1717: [HALRXF] %s: Wrong %s(%d)
Line 1718: [HALRXF] %s: Wrong %s(%d)
Line 1719: [HALRXF] %s: Wrong %s(%d)
Line 1720: [HALRXF] %s: Wrong %s(%d)
Line 1745: [HALRXF] DVGA[ENABLE]: BYPASS(0x%X)
Line 1755: [HALRXF] DVGA[ENABLE]: RXF_DVGA[%d].OFFSET(0x%X)
Line 1756: [HALRXF] DVGA[ENABLE]: RXF_DVGA[%d].OFFSET(0x%X)
Line 1766: [HALRXF] DVGA[ENABLE]: OFFSET_DELAY_OV(0x%X)
Line 1791: [HALRXF] %s: Wrong %s(%d)
Line 1817: [HALRXF] DVGA[ENABLE]: rf_path(0x%X), OFFSET_TICK_MODE(0x%X), dvga_dly(0x%X)
Line 1861: [HALRXF] DVGA[ENABLE]: Wrong Rat(%d)
Line 1871: [HALRXF] DVGA[ENABLE]: rat(%d), mxr_sel(%d), enable(%d), bw(%d), rx_mode(%d)
Line 1897: [HALRXF] %s: Wrong %s(%d)
Line 1898: [HALRXF] %s: Wrong %s(%d)
Line 1949: [HALRXF] ConfigDVGA_Hys: Wrong Rat(%d)
Line 1981: [HALRXF] %s: Wrong %s(%d)
Line 2011: [HALRXF] SRRCF[INIT]: rat(%d)
Line 2038: [HALRXF] %s: Wrong %s(%d)
Line 2039: [HALRXF] %s: Wrong %s(%d)
Line 2040: [HALRXF] %s: Wrong %s(%d)
Line 2041: [HALRXF] %s: Wrong %s(%d)
Line 2066: [HALRXF] SRRCF[ENABLE]: BYPASS(0x%X)
Line 2074: [HALRXF] SRRCF[ENABLE]: rat(%d), mxr_sel(%d), enable(%d), rx_mode(%d)
Line 2094: [HALRXF] %s: Wrong %s(%d)
Line 2095: [HALRXF] %s: Wrong %s(%d)
Line 2121: [HALRXF] IQC[DISABLE]: Wrong Rat(%d)
Line 2138: [HALRXF] IQC[DISABLE]: rat(%d), iqc_sel(%d)
Line 2158: [HALRXF] %s: Wrong %s(%d)
Line 2159: [HALRXF] %s: Wrong %s(%d)
Line 2191: [HALRXF] IQC[INIT]: IQC_OPERATION_SET(0x%X)
Line 2210: [HALRXF] IQC[INIT]: IQC_OPERATION_SET(0x%X)
Line 2237: [HALRXF] IQC[INIT]: IQC_OPERATION_SET(0x%X)
Line 2261: [HALRXF] IQC[INIT]: IQC_OPERATION_SET_CDMA(0x%X)
Line 2268: [HALRXF] IQC[INIT]: Wrong Rat(%d)
Line 2278: [HALRXF] IQC[INIT]: rat(%d), iqc_sel(%d)
Line 2298: [HALRXF] %s: Wrong %s(%d)
Line 2299: [HALRXF] %s: Wrong %s(%d)
Line 2326: [HALRXF] IQC[ENABLE]: IQC_OPERATION_SET_CC(0x%X)
Line 2342: [HALRXF] IQC[ENABLE]: IQC_OPERATION_SET_CC(0x%X)
Line 2358: [HALRXF] IQC[ENABLE]: IQC_OPERATION_SET_CC(0x%X)
Line 2375: [HALRXF] IQC[ENABLE]: IQC_OPERATION_SET_CDMA(0x%X)
Line 2382: [HALRXF] IQC[ENABLE]: Wrong Rat(%d)
Line 2392: [HALRXF] IQC[ENABLE]: rat(%d), iqc_sel(%d)
Line 2412: [HALRXF] %s: Wrong %s(%d)
Line 2413: [HALRXF] %s: Wrong %s(%d)
Line 2431: [HALRXF] IQC[OVR]: Wrong Rat(%d)
Line 2441: [HALRXF] IQC[OVR]: rat(%d), iqc_sel(%d)
Line 2461: [HALRXF] %s: Wrong %s(%d)
Line 2475: [HALRXF] %s: Wrong %s(%d)
Line 2483: [HALRXF] IQC[RESET]: IQC_OPERATION_SET_CC(0x%X)
Line 2496: [HALRXF] IQC[RESET]: IQC_OPERATION_SET_CDMA(0x%X)
Line 2502: [HALRXF] IQC[RESET]: Wrong Rat(%d)
Line 2511: [HALRXF] IQC[RESET]: rat(%d), iqc_sel(%d)
Line 2533: [HALRXF] %s: Wrong %s(%d)
Line 2597: [HALRXF] IQD[INIT]: Wrong Rat(%d)
Line 2610: [HALRXF] IQD[INIT]: RFD_RXF_IQD_x(0x%X)
Line 2618: [HALRXF] IQD[INIT]: rat(%d)
Line 2638: [HALRXF] %s: Wrong %s(%d)
Line 2639: [HALRXF] %s: Wrong %s(%d)
Line 2663: [HALRXF] DCR[DISABLE]: Wrong Rat(%d)
Line 2693: [HALRXF] DCR[DISABLE]: rat(%d), dcr_sel(%d)
Line 2715: [HALRXF] %s: Wrong %s(%d)
Line 2716: [HALRXF] %s: Wrong %s(%d)
Line 2813: [HALRXF] DCR[INIT]: Wrong Rat(%d)
Line 2822: [HALRXF] DCR[INIT]: rat(%d), dcr_sel(%d)
Line 2844: [HALRXF] %s: Wrong %s(%d)
Line 2867: [HALRXF] DCR INPUT[INIT]: rat(%d)
Line 2889: [HALRXF] %s: Wrong %s(%d)
Line 2890: [HALRXF] %s: Wrong %s(%d)
Line 2910: [HALRXF] DCR[ENABLE]: RFD_DCR_OPERATION_SET_CC%d(0x%X)
Line 2918: [HALRXF] DCR[ENABLE]: rat(%d), dcr_sel(%d)
Line 2942: [HALRXF] %s: Wrong %s(%d)
Line 2943: [HALRXF] %s: Wrong %s(%d)
Line 2974: [HALRXF] DCR[OVR]: rat(%d), dcr_sel(%d)
Line 2994: [HALRXF] DCRAntOverride
Line 3003: [HALRXF] DCROverride
Line 3023: [HALRXF] %s: Wrong %s(%d)
Line 3024: [HALRXF] %s: Wrong %s(%d)
Line 3051: [HALRXF] DCR[RESET]: rat(%d), dcr_sel(%d)
Line 3075: [HALRXF] %s: Wrong %s(%d)
Line 3084: [HALRXF] %s: Wrong %s(%d)
Line 3085: [HALRXF] %s: Wrong %s(%d)
Line 3086: [HALRXF] %s: Wrong %s(%d)
Line 3087: [HALRXF] %s: Wrong %s(%d)
Line 3121: [HALRXF] SyncDCF: RXF_SYNC_4G.MODE(%x), RXF_SYNC_4G.SCALING_BYPASS(%d), RXF_SYNC_AGC_SET.MODE(%x)
Line 3136: [HALRXF] SyncDCF: Worng Rat(%d)
Line 3148: [HALRXF] SyncDCF: rat(%d), mxr(%d), mode(%d), bw(%d)
Line 3168: [HALRXF] %s: Wrong %s(%d)
Line 3169: [HALRXF] %s: Wrong %s(%d)
Line 3186: [HALRXF] AGC[DISABLE]: rat(%d), mxr_sel(%d)
Line 3205: [HALRXF] %s: Wrong %s(%d)
Line 3206: [HALRXF] %s: Wrong %s(%d)
Line 3239: [HALRXF] %s: Wrong %s(%d)
Line 3240: [HALRXF] %s: Wrong %s(%d)
Line 3266: [HALRXF] AGCAccReset: Wrong Rat(%d)
Line 3314: [HALRXF] %s: Wrong %s(%d)
Line 3315: [HALRXF] %s: Wrong %s(%d)
Line 3316: [HALRXF] %s: Wrong %s(%d)
Line 3477: [HALRXF] AGC[INIT]: Wrong Rat(%d)
Line 3486: [HALRXF] AGC[INIT]: rat(%d), mxr_sel(%d), dcr_sel(%d)
Line 3506: [HALRXF] %s: Wrong %s(%d)
Line 3507: [HALRXF] %s: Wrong %s(%d)
Line 3541: [HALRXF] AGC[ENABLE]: Wrong Rat(%d)
Line 3550: [HALRXF] AGC[ENABLE]: rat(%d), mxr_sel(%d), dcr_sel(%d)
Line 3570: [HALRXF] %s: Wrong %s(%d)
Line 3571: [HALRXF] %s: Wrong %s(%d)
Line 3582: [HALRXF] AGC[OV]: agc_value[0]: OV(0x%X), WR(0x%X), START(0x%X)
Line 3583: [HALRXF] AGC[OV]: agc_value[1]: OV(0x%X), WR(0x%X), START(0x%X)
Line 3592: [HALRXF] AGC[OV]: rat(%d), mxr_sel(%d)
Line 3615: [HALRXF] %s: Wrong %s(%d)
Line 3616: [HALRXF] %s: Wrong %s(%d)
Line 3658: [HALRXF] AGC[RESET]: Wrong Rat(%d)
Line 3667: [HALRXF] AGC[RESET]: rat(%d), mxr_sel(%d)
Line 3690: [HALRXF] %s: Wrong %s(%d)
Line 3691: [HALRXF] %s: Wrong %s(%d)
Line 3703: [HALRXF] %s: Wrong %s(%d)
Line 3704: [HALRXF] %s: Wrong %s(%d)
Line 3760: [HALRXF] ConfigAGC_Hys: Wrong mode(%d)
Line 3798: [HALRXF] ConfigAGC_Hys: Wrong Rat(%d)
Line 3830: [HALRXF] %s: Wrong %s(%d)
Line 3980: [HALRXF] MIXER[INIT]: Wrong Rat(%d)
Line 3990: [HALRXF] MIXER[INIT]: rat(%d)
Line 4021: [HALRXF] %s: Wrong %s(%d)
Line 4022: [HALRXF] %s: Wrong %s(%d)
Line 4023: [HALRXF] %s: Wrong %s(%d)
Line 4024: [HALRXF] %s: Wrong %s(%d)
Line 4025: [HALRXF] %s: Wrong %s(%d)
Line 4050: [HALRXF] MIXER[ENABLE]: BYPASS(0x%X)
Line 4065: [HALRXF] MIXER[ENABLE]: RXF_MIXER_NEXT(0x%08x)
Line 4089: [HALRXF] %s: Wrong %s(%d)
Line 4213: [HALRXF] MIXER[ENABLE]: Wrong Rat(%d)
Line 4230: [HALRXF] MIXER[ENABLE]: rf(%d), dcr(%d), mxr(%d), enable(%d), bw(%d), rx_mode(%x)
Line 4256: [HALRXF] %s: Wrong %s(%d)
Line 4280: [HALRXF] ConfigExtLNA[ENABLE]: Wrong Rat(%d)
Line 4312: [HALRXF] %s: Wrong %s(%d)
Line 4339: [HALRXF] ConfigExtLNA_Hys: Wrong Rat(%d)
Line 4369: [HALRXF] %s: Wrong %s(%d)
Line 4408: [HALRXF] PEQ[INIT]: Worng Rat(%d)
Line 4417: [HALRXF] PEQ[INIT]: rat(%d)
Line 4441: [HALRXF] %s: Wrong %s(%d)
Line 4468: [HALRXF] TFR[INIT]: Worng Rat(%d)
Line 4477: [HALRXF] TFR[INIT]: rat(%d)
Line 4497: [HALRXF] %s: Wrong %s(%d)
Line 4510: [HALRXF] %s: Wrong %s(%d)
Line 4533: [HALRXF] ConfigCDMA[INIT]: Worng Rat(%d)
Line 4542: [HALRXF] ConfigCDMA[INIT]: rat(%d), rx_mode(%d)
Line 4566: [HALRXF] SetAgcCDMA: RXF_CDMA_AGC_3GC(0x%x)
Line 4596: [HALRXF] %s: Wrong %s(%d)
Line 4597: [HALRXF] %s: Wrong %s(%d)
Line 4598: [HALRXF] %s: Wrong %s(%d)
Line 4632: [HALRXF] SetGainSplitter: Wrong Rat(%d)
Line 4646: [HALRXF] SetGainSplitter: dcr(%d), rx_mode(%d), GAIN_SPLITTER(%X)
Line 4681: [HALRXF] %s: Wrong %s(%d)
Line 4682: [HALRXF] %s: Wrong %s(%d)
Line 4693: [HALRXF] SetPgcRamTable: RXF_PGC_MODE[%d](0x%X)
Line 4746: [HALRXF] SetPgcRamTable: length %d PGC_RAM_ADDR 0x%X gain_word[%d][%d] 0x%0X
Line 4748: pgc_addr_rf[%d] 0x%x
Line 4753: [HALRXF] SetPgcRamTable: Wrong Rat(%d)
Line 4796: [HALRXF] SetPgcRamTable: RAM%d[%d] = WR(0x%x, 0x%x), RD(0x%x, 0x%x)
Line 4842: [HALRXF] SetPgcRamTable: d2d_pgc_sel(%d), band(%d -> %d), pgc_sel(%d), ram(%d, %d), size(%d)
Line 4870: [HALRXF] %s: Wrong %s(%d)
Line 4871: [HALRXF] %s: Wrong %s(%d)
Line 4872: [HALRXF] %s: Wrong %s(%d)
Line 4898: agc_sel %d agc_pgc[0] 0x%x agc_pgc[1] 0x%x pgc_addr_rf 0x%x
Line 4908: [HALRXF] SetPgcRamSel: RXF_AGC_PGC_ANT[%d](0x%X), RXF_AGD_PGC_ANT[%d](0x%X)
Line 4926: [HALRXF] SetPgcRamSel: dcr(%d),agc(%d) pgc(%d), Pgc_ram_sel(%d, %d)
Line 4954: [HALRXF] %s: Wrong %s(%d)
Line 4955: [HALRXF] %s: Wrong %s(%d)
Line 4974: [HALRXF] SetAgcHys: HYS_RISE_ANT[%d](0x%X)
Line 4988: [HALRXF] SetAgcHys: HYS_FALL_ANT[%d](0x%X)
Line 5007: [HALRXF] %s: Wrong %s(%d)
Line 5008: [HALRXF] %s: Wrong %s(%d)
Line 5020: [HALRXF] SetAgcHys: ANT_INDEX(0x%X)
Line 5035: [HALRXF] SetAgcHys: Wrong Rat(%d)
Line 5048: [HALRXF] SetAgcHys: dcr(%d), enable(%d)
Line 5076: [HALRXF] %s: Wrong %s(%d)
Line 5077: [HALRXF] %s: Wrong %s(%d)
Line 5078: [HALRXF] %s: Wrong %s(%d)
Line 5079: [HALRXF] %s: Wrong %s(%d)
Line 5258: [HALRXF] SetAgcAntInput: Wrong Rat(%d)
Line 5269: [HALRXF] SetAgcAntInput: avg_sel(%08x) avg_input(%08x, %08x)
Line 5277: [HALRXF] SetAgcAntInput: agc_ant_input(0x%08X, 0x%08X, 0x%08X, 0x%08X, 0x%08X)
Line 5290: [HALRXF] SetAgcAntInput: rx_mode(%d), rf(%d), mxr(%d), bw(%d)
Line 5310: [HALRXF] %s: Wrong %s(%d)
Line 5340: [HALRXF] SetInterpolator: Wrong Rat(%d)
Line 5389: [HALRXF] %s: Wrong %s(%d)
Line 5430: [HALRXF] %s: Wrong %s(%d)
Line 5431: [HALRXF] %s: Wrong %s(%d)
Line 5635: [HALRXF] SetFbRx: fbDumpA(%X), fbDumpAccL(%X), fbAccL1(%X), fbAccL2(%X)
Line 5731: [HALRXF] SetFbRx: Info->rf_path = %d, RxfInfo.dcr_sel = %d, rfd_sampling_rate = 0x%x, fbrxSamplingRate = 0x%x, fbrxADC = 0x%x
Line 5772: [HALRXF] SetFbRx#2: RFD_FBRX_INPUT_SEL = 0x%x, RFD_FBRX_INOUT_SEL = 0x%x, RFD_DIF_OUT_DATA_SEL_F = 0x%x
Line 5937: [HALRXF] SetFbRx: Wrong Rat(%d)
Line 5953: [HALRXF] SetFbRx: enable(%d), rf(%d), dcr(%d), mode(%x), bw(%d)
Line 5977: [HALRXF] %s: Wrong %s(%d)
Line 5978: [HALRXF] %s: Wrong %s(%d)
Line 6047: [HALRXF] %s: Wrong %s(%d)
Line 6048: [HALRXF] %s: Wrong %s(%d)
Line 6075: [HALRXF] SetDvgaHys: GAIN_MAPPER(0x%X)
Line 6084: [HALRXF] SetDvgaHys: GAIN_INDEX_HYS_FALL (0x%X)
Line 6093: [HALRXF] SetDvgaHys: GAIN_INDEX_HYS_RISE (0x%X)
Line 6108: [HALRXF] SetDvgaHys: GAIN_INDEX_HYS_ENABLE_GAIN_LEVELMAPPER (0x%X)
Line 6136: [HALRXF] SetDvgaHys: enable(%d), hys(%d, %d, %d, %d, %d)
Line 6155: [HALRXF] %s: Wrong %s(%d)
Line 6276: [HALRXF] SetPowMeas: Wrong Rat(%d)
Line 6286: [HALRXF] SetPowMeas: rat(%d)
Line 6304: [HALRXF] %s: Wrong %s(%d)
Line 6305: [HALRXF] %s: Wrong %s(%d)
Line 6319: [HALRXF] SetDif: dif(0x%X)
Line 6349: [HALRXF] %s: Wrong %s(%d)
Line 6360: [HALRXF] SetModeSetChange HALRXF_GetUsingCCNum cnt(%d) currentIPLL(%d)
Line 6365: [HALRXF] SetModeSetChange : HALF -> FULL
Line 6370: [HALRXF] SetModeSetChange : FULL -> HALF
Line 6387: [HALRXF] SetModeSetChange dcr_sel(%d) dif_out_data_sel(0x%X)
Line 6406: [HALRXF] SetModeSetChange feedbackread(0x%X)
Line 6414: [HALRXF] SetModeSetChange dcr_sel(%d), ratsamplingchanged(%d)
Line 6438: [HALRXF] %s: Wrong %s(%d)
Line 6439: [HALRXF] %s: Wrong %s(%d)
Line 6480: [HALRXF] SetRxFilterOutput: FFT_INPUT_SEL[%d](0x%X)
Line 6563: [HALRXF] SetRxFilterOutput: Wrong Rat(%d)
Line 6576: [HALRXF] SetRxFilterOutput(CC%d): mxr(%d)
Line 6640: [HALRXF] ReOrderFftInputSelFor2Rx: mxr_sel(%d, %d), output_sel(%d, %d), FFT_INPUT_SEL(%x, %x)
Line 6663: [HALRXF] %s: Wrong %s(%d)
Line 6664: [HALRXF] %s: Wrong %s(%d)
Line 6665: [HALRXF] %s: Wrong %s(%d)
Line 6717: [HALRXF] SetDcrSel: RFD_DCR_DATA_SEL(0x%X), RXF_ADC_SEL(0x%X)
Line 6735: [HALRXF] SetDcrSel: rf_path(%d), dcr(%d), rx_mode(%d), enable(%d)
Line 6759: [HALRXF] %s: Wrong %s(%d)
Line 6760: [HALRXF] %s: Wrong %s(%d)
Line 6792: [HALRXF] SetAgcMode: AGC_MODE_SET_CC[%d](0x%X)
Line 6818: [HALRXF] AGC[ENABLE]: Wrong Rat(%d)
Line 6827: [HALRXF] SetAgcMode: rat(%d)
Line 6851: [HALRXF] %s: Wrong %s(%d)
Line 6852: [HALRXF] %s: Wrong %s(%d)
Line 6866: [HALRXF] HALRXF_SetDVGADelayOffset: dvgaOffset(%d) 
Line 6890: [HALRXF] %s: Wrong %s(%d)
Line 6891: [HALRXF] %s: Wrong %s(%d)
Line 6905: [HALRXF] SetDVGAOffset: dvgaOffset(%d) 
Line 6945: [HALRXF] SetDVGAMode: Wrong Rat(%d)
Line 6955: [HALRXF] SetDVGAMode: dvgaOffset
Line 7028: [HALRXF] %s: Wrong %s(%d)
Line 7029: [HALRXF] %s: Wrong %s(%d)
Line 7066: [HALRXF] GetMxrBw: Wrong Rat(%d)
Line 7075: [HALRXF] GetMxrBw: bw(%d)
Line 7125: [HALRXF] SetAGCUpdateRate: Wrong Rat(%d)
Line 7134: [HALRXF] SetAGCUpdateRate: rat(%d)
Line 7183: [HALRXF] SetAGCAccLength: Wrong Rat(%d)
Line 7192: [HALRXF] SetAGCAccLength: rat(%d)
Line 7245: [HALRXF] SetAGCLoopGain: Wrong Rat(%d)
Line 7255: [HALRXF] SetAGCLoopGain: SHIFT_K(0x%x)
Line 7308: [HALRXF] SetAGCRefOffset: Wrong Rat(%d)
Line 7317: [HALRXF] SetAGCRefOffset: REF_OFFSET(0x%x)
Line 7346: [HALRXF] SetClk245: RXF_CLK245_ON(0x%X)
Line 7376: [HALRXF] %s: Wrong %s(%d)
Line 7377: [HALRXF] %s: Wrong %s(%d)
Line 7378: [HALRXF] %s: Wrong %s(%d)
Line 7426: [HALRXF] SetExtLnaMode: rf(%d), dcr(%d), j(%d), mode(%d), offset[0](%d), offset[1](%d), offset[2](%d)
Line 7454: [HALRXF] %s: Wrong %s(%d)
Line 7455: [HALRXF] %s: Wrong %s(%d)
Line 7456: [HALRXF] %s: Wrong %s(%d)
Line 7493: [HALRXF] SetExtLnaMode: rf(%d),mode(%d), offset[0](%d), offset[1](%d), offset[2](%d)
Line 7521: [HALRXF] %s: Wrong %s(%d)
Line 7522: [HALRXF] %s: Wrong %s(%d)
Line 7557: [HALRXF] SetExtLnaModeOvr: rf(%d), dcr(%d), num(%d), ov(%d), wr(%d)
Line 7584: [HALRXF] %s: Wrong %s(%d)
Line 7585: [HALRXF] %s: Wrong %s(%d)
Line 7623: [HALRXF] SetExtLnaHys: rf(%d), dcr(%d), num(%d), hys[0,1](%d), hys[2,3](%d), hys[4,5](%d)
Line 7648: [HALRXF] %s: Wrong %s(%d)
Line 7649: [HALRXF] %s: Wrong %s(%d)
Line 7679: [HALRXF] SetExtLnaHysfor3G: rf(%d), hys[0,1](%d), hys[2,3](%d), hys[4,5](%d)
Line 7729: [HALRXF] SetExtLnaTickMode: Wrong Rat(%d)
Line 7738: [HALRXF] SetExtLnaTickMode: RXF_EXT_LNA_TICK_MODE(0x%X)
Line 7760: [HALRXF] %s: Wrong %s(%d)
Line 7761: [HALRXF] %s: Wrong %s(%d)
Line 7781: [HALRXF] SetIqcCoefValue: OV_ANT(%x), TAP(%d), I(%x), Q(%x)
Line 7793: [HALRXF] SetIqcCoefValue: OV_ANT(%x), TAP(%d), I(%x), Q(%x)
Line 7809: [HALRXF] SetIqcCoefValue: rat(%d), iqc(%d), coef[0](%d), coef[1](%d), coef[2](%d)
Line 7839: [HALRXF] %s: Wrong %s(%d)
Line 7840: [HALRXF] %s: Wrong %s(%d)
Line 7858: [HALRXF] GetIqcCoefValue(%d): TAP(%d), I(%x), Q(%x)
Line 7871: [HALRXF] GetIqcCoefValue: rat(%d), iqc(%d)
Line 7951: [RXF] GetMxrSelList: rf(%d), mxr(%d, %d), mode(%d)
Line 8038: [RXF] SetADC: rf(%d), mode(%d), bw(%d)
Line 8300: [HALRXF_SetFbRx] RFD_FBRX_SAMPLING_MODE 0x%x, RFD_RXF_RAT_0 0x%x, RFD_RXF_RAT_5 0x%x, RFD_MPLL_CLK_SEL_CC0 0x%x, RFD_MPLL_CLK_SEL_CC5 0x%x, RFD_FBRX_DCR0 0x%x, RFD_FBRX_DCR1 0x%x
Line 8310: [HALRXF_SetFbRx] RFD_FBRX_AGC0 0x%x, RFD_FBRX_AGC1 0x%x, RFD_FBRX_INOUT_SEL 0x%x, RFD_FBRX_INPUT_SEL 0x%x, RFD_DCR_CON_5 0x%x, RFD_MPLL_CLK_SEL_CDMA 0x%x, FBRX_SAMPLING_MODE 0x%x
Line 8320: [ADC CC0] Dump MSpeedy = 0x%03x , 0x%08x
Line 8326: [ADC CC5] Dump MSpeedy = 0x%03x , 0x%08x
Line 8332: [ADC CC7] Dump MSpeedy = 0x%03x , 0x%08x
Line 8391: [HALRXF] HALRXF_GetUsingCCNum : 3CC SLO Case
Line 8398: [HALRXF] HALRXF_GetUsingCCNum : 2CC SLO Case
Line 8404: [HALRXF] HALRXF_GetUsingCCNum : NR CASE
