Line 406: [SYSTEM] InitSystemTime: RTG offset(%d)
Line 545: [SYSTEM] SetDlSystemInfo(RXF%d): sys_info(%08x -> %08x)
Line 585: [SYSTEM] SetDlSystemInfo(RXF%d RFD%d CC0_HENB): HENB_SYSTEM_INFO(%08x -> %08x)
Line 683: [SYSTEM] SetDlSystemInfo(RFD%d): sys_info(%08x -> %08x)
Line 701: [SYSTEM] SetDlSystemInfo(RX%d RF%d): sys_info(%08x -> %08x)
Line 865: [SYSTEM] SetDrxMode(RX%d): mode(%d)
Line 905: [SYSTEM] SetDrxStartPos: mode(%d), time(0x%x), drx_counter(0x%x), SFN(%d), TTI(%d), Offset(%d)
Line 967: [SYSTEM] SetIratTriggerSignal: enable(%d), time(%08x), len(%d)
Line 1011: [SYSTEM] SetRtgLoad : not workaround for AGAP
Line 1131: [SYSTEM] SetRtgLoad [WR](RTG%d, RFD_RTG%d): RTG(%x %x) diff(%d)
Line 1142: [SYSTEM] SetRtgLoad(RTG%d, RFD_RTG%d): offset(%d)
Line 1367: [SYSTEM] ConfigRtg(DEBUG): rtg_counter(%d), gen_counter(%d), general_snap(%d), cur_sfn(%d)
Line 1390: [SYSTEM] ConfigRtg(RTG%d): offset(%d), copy(%x), bw(%d), diff(%d), rtg(%d -> %d)
Line 1664: [SYSTEM] RTG%d: bw(%d), diff(%d), rtg(%d -> %d)
Line 1704: [SYSTEM] AlignRtg(RTG%d)
Line 1807: [SYSTEM] CopyRtg(%d)(RTG%d -> RTG%d)[shift %d]
Line 1908: [SYSTEM] SetSfn(RTG%d) (RFD%d): sfn(%d)
Line 2297: [SYSTEM] EnableSysTimeIntr(%d): mode(0x%x), time(0x%x)
Line 2380: [SYSTEM] CheckSysTimeCommonIntr: en(0x%08x), pend(0x%08x)
Line 2647: [SYSTEM] SetGapMode(CC%d): mode(%d), bw(%d), length(%d), sfn_tti(%d), offset(%d,%d)
Line 2757: [SYSTEM] SetCaMode(CC%d): on(%d, 0x%x), time(%d), tti_config(0x%x)
Line 2822: [SYSTEM] SetSloOn(CC%d): on(%d) DIG_ON(0x%x)
Line 2919: [SYSTEM] SetAgcAntSel(RF%d): rtg(%d), path_enable(%x, %x)
Line 3003: [SYSTEM] SetTrxSwitch(RF%d): rtg(%d), sys_info(%08x) dlul_BB(%08x) uldl_BB(%08x) dlul_RFD(%08x) uldl_RFD(%08x)
Line 3013: [SYSTEM] SetTrxSwitch(RF%d): rtg(%d), sys_info(%08x)
Line 3197: [SYSTEM] HAL_CheckCcGroupingInfo(0x%x): RTG0(%d), RTG1(%d), RTG2(%d), RTG3(%d), RTG4(%d), RTG5(%d)
Line 3198: [SYSTEM] HAL_CheckCcGroupingInfo(0x%x): RTG6(%d), RTG7(%d), RTG8(%d), RTG9(%d)
Line 3199: [SYSTEM] HAL_CheckCcGroupingInfo : CC0(%d), CC1(%d), CC2(%d), CC3(%d), CC4(%d), CC5(%d)
Line 3200: [SYSTEM] HAL_CheckCcGroupingInfo : CC6(%d), CC7(%d), CC8(%d), CC9(%d)
Line 3226: [RXF] SetTrxOverrideMode(%d):(0x%08x)
Line 3274: [RXF] HAL_SetTrxModeToDl(%d): rf(%d), TRX_CFG_ON(0x%08x), TRX_CFG_OFF(0x%08x)
Line 3298: [RXF] HAL_SetRxfSloDelay(%d): 5M(%d), 10M(%d), 15M(%d), 20M(%d)
Line 3334: [SYSTEM] PATH_ENABLE_4G : rtg(%d), path_enable(%x, %x)
