Line 2: Create timer [ %s ], Duration [ %d ]
Line 3: Create timer [ %s ], Duration [ %d ]
Line 4: Create timer [ %s ], Duration [ %d ]
Line 5: Create timer [ %s ], Duration [ %d ]
Line 6: Create timer [ %s ], Duration [ %d ]
Line 7: Create timer [ %s ], Duration [ %d ]
Line 8: Create timer [ %s ], Duration [ %d ]
Line 9: Create timer [ %s ], Duration [ %d ]
