Line 110: RemoveSessionIdFromList() : Not found SessionId(0x%x)
Line 129: SetSessionSvcState() : No suitable New State(%d)
Line 147: SetSessionSvcState() : Not Founded, New State(%d)
Line 160: GetSessionSvcState() : Not Founded SessionId(0x%x) State(%d)
Line 173: GetSessionSvcState() : Not Founded SessionId(0x%x) State(%d)
Line 186: GetSessionSvcState() : Not Founded SessionId(0x%x) State(%d)
