Line 101: [NR IPC] PHY_L1C_LCPU_INIT_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d) NrStatus(%d)
Line 120: [NR IPC] L1C_PHY_LCPU_INIT_CNF, BM_SrcCcForCnfMsg(%d)
Line 139: [NR IPC] PHY_L1C_LCPU_INIT_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), NrStatus(%d)
Line 147: (I)Received CcInfoBitmap Table in HEX (CC_Idx/Processor_Idx/Demod_Idx) 0:(0x%X), 1:(0x%X), 2:(0x%X), 3:(0x%X), 4:(0x%X), 5:(0x%X), 6:(0x%X)
Line 157: (I)Received CcInfoBitmap Table in HEX (CC_Idx/Processor_Idx/Demod_Idx) 7:(0x%X), 8:(0x%X)
Line 166: (F)Fail to update CC Info Table
Line 169: (I)CC Index mapping info of My processor: MyProcessor(%d) cc_offset(0)->%d, cc_offset(1)->%d
Line 268: [NR IPC] PHY_L1C_LCPU_RELEASE_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 311: [NR IPC] IPC_NR_STATUS_IND_REQ Initialize(to LTE), BM_SrcCcForCnfMsg(%d)
Line 370: [NR IPC] PHY_L1C_LCPU_STORE_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 416: [NR IPC] PHY_L1C_LCPU_RESTORE_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 461: [NR IPC] PHY_L1C_CELLGROUP_COMMON_CONFIG_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 499: [NR IPC] L1C_PHY_CELLGROUP_COMMON_CONFIG_CNF, BM_SrcCcForCnfMsg(%d)
Line 535: [NR IPC] PHY_L1C_CELLGROUP_PCELL_CONFIG_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 570: [NR IPC] NR_ServingCellConfig_csi_MeasConfig is OFF
Line 584: [NR IPC] L1C_PHY_CELLGROUP_PCELL_CONFIG_CNF, BM_SrcCcForCnfMsg(%d)
Line 619: [NR IPC] PHY_L1C_CELLGROUP_SCELL_CONFIG_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 674: [NR IPC] PHY_L1C_SCELL_ACTDEACT_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 692: [NR IPC] Force to change BW from over NUM_NR_SYS_BW ->(%d)
Line 741: [NR IPC] PHY_L1C_SIB1_PCELL_CONFIG_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 779: [NR IPC] L1C_PHY_SIB1_PCELL_CONFIG_CNF, BM_SrcCcForCnfMsg(%d)
Line 815: [NR IPC] PHY_L1C_TDP_CONFIG_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 861: [NR IPC] PHY_L1C_RXMODE_CHANGE_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 910: [NR IPC] PHY_L1C_DATA_INACTIVE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 955: [NR IPC] PHY_L1C_UL_ACTIVATION_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1004: [NR IPC] PHY_L1C_TX_SWAP_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1053: [NR IPC] PHY_L1C_DL_NTM_MEASURE, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1084: [NR IPC] IPC_NR_GAP_CTRL_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1128: [NR IPC] PHY_L2_MAC_RESET_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1225: [NR IPC] PHY_L2_MAC_RACH_CONTROL_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1275: [NR IPC] IPC_NR_RNTI_CONTROL_IND_t, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1322: [NR IPC] PHY_PHY_RNTI_CFG_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1369: [NR IPC] PHY_PHY_RACH_TX_INFO_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1410: [NR IPC] PHY_PHY_RA_CrStateUpdate_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1453: [NR IPC] PHY_PHY_RACH_M4_GRANT_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1497: [NR IPC] PHY_PHY_RA_CFG_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1543: [NR IPC] PHY_PHY_RA_CrStateReport_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1590: [NR IPC] PHY_PHY_RA_CrStateReport_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1634: [NR IPC] PHY_L2_TA_CONTROL_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1703: [NR IPC] PHY_L1C_DRX_CMD_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1748: [NR IPC] PHY_L2_SR_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1842: [NR IPC] PHY_L2_SP_CSIRS_CSIIM_ACT_DEACT_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1888: [NR IPC] PHY_L2_A_CSI_TRG_SUBSET_SUBSEL_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1980: [NR IPC] PHY_L2_PDSCH_TCI_STATES_ACT_DEACT_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2025: [NR IPC] PHY_L2_PDCCH_TCI_STATE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2071: [NR IPC] PHY_L2_PUCCH_SRS_RELEASE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2120: [NR IPC] PHY_L2_UE_BEAMLOCK_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2197: [NR IPC] PHY_L1C_MIB_ACQ_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2269: [NR IPC] PHY_L1C_QSLEEP_CTRL_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2313: [NR IPC] PHY_L1C_SYS_PARAM_CHANGE_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2410: [NR IPC] PHY_L1C_BWP_CHANGE_DONE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2470: [NR IPC] PHY_L1C_SIB1_ACQ_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2499: [NR IPC] L1C_PHY_SIB1_ACQ_CNF, BM_SrcCcForCnfMsg(%d)
Line 2536: [NR IPC] PHY_L1C_SIBX_ACQ_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2565: [NR IPC] L1C_PHY_SIBX_ACQ_CNF, BM_SrcCcForCnfMsg(%d)
Line 2601: [NR IPC] PHY_L1C_MEAS_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2648: [NR IPC] PHY_L1C_MTC_INFO_IND, FreqRange(%d) RsType(%d) SmtcSfn(%d) RxBeamIdx(%d) smtc_duration(%d) ssbbit[0/1](%d/%d)
Line 2690: [NR IPC] PHY_L1C_DRX_CFG_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2732: [NR IPC] PHY_L1C_DRX_WAKEUP_INIT_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2918: [NR IPC] PHY_PHY_NR_LTE_TXPOWER_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2962: [NR IPC] PHY_L1C_SAR_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 3007: [NR IPC] PHY_L1C_NTM_MODE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 3056: [NR IPC] PHY_L1C_NTM_SET_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 3105: [NR IPC] PHY_L1C_PHY_TEST_MODE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 3155: [NR IPC] PHY_L1C_TMU_CTRL_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 3199: [NR NTM] NrRcvSelfIpcHndlr_NtmMeasureReport: PHY_PHY_NTM_MEASURE_REPORT
Line 3206: [NR NTM] NrRcvSelfIpcHndlr_NtmMeasureReport: cc_offset = %d cc_idx = %d TARGET_CC_BITMAP.cc_idx = 0x%x, 
Line 3210: [NR NTM] =====[NR_IPC]===== PHY_PHY_NTM_MEASURE_REPORT: CcIndex(%d), MsgId(%d)
Line 3328: =====[NR_IPC_SELF]===== (RCV) PHY_PHY_UPDATE_CC_TPUT_RATIO_IND: CcIndex(%d), MsgId(%d)
Line 3392: [NR IPC] PHY_PHY_ThermalLevelMeasure, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), level(%d)
Line 3760: [NR IPC] PHY_L1C_STORE_PHY_CONFIG_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), validflag(%d)
Line 3784: [NR IPC] L1C_PHY_STORE_PHY_CONFIG_CNF, BM_SrcCcForCnfMsg(%d)
Line 3819: [NR IPC] PHY_L1C_RESTORE_PCELL_PHY_CONFIG_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d) validflag_bmp(%d)
Line 3940: [NR IPC] L1C_PHY_RESTORE_PCELL_PHY_CONFIG_CNF, BM_SrcCcForCnfMsg(%d)
Line 3980: [NR IPC] PHY_L1C_TX_SUSPEND_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4025: [NR IPC] PHY_L1C_TX_RESUME_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4069: [NR IPC] PHY_L1C_CONN_PRIO_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4434: [NR IPC] PHY_PHY_RACH_ASLOT_INFO2HBF_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4501: [NR IPC] PHY_PHY_LCPU_RELEASE_READY, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4544: [NR IPC] L1C_PHY_LCPU_RELEASE_CNF, BM_SrcCcForCnfMsg(%d)
Line 4563: [NR IPC] IPC_NR_STATUS_IND_REQ Release (to LTE), BM_SrcCcForCnfMsg(%d)
Line 4660: =====[NR_IPC_SELF]===== (RCV) PHY_PHY_NR_HBUF_UPDATE_REQ: MsgId(%d)
Line 4690: [NR IPC] PHY_PHY_BWP_SWITCHING_CTRL_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4767: [NR IPC] PHY_PHY_CE_SCRAMBSEQ_CALC_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4805: [NR IPC] PHY_PHY_CCH_RECONFIG_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4924: =====[NR_IPC_SELF]===== NrRcvSelfIpcHndlr_MeasDoneInd, cc_idx: %d
Line 4951: [NR IPC] NrRcvSelfIpcHndlr_SysParamchgCfgdone, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 5000: [NR IPC] NrRcvSelfIpcHndlr_ScellStatusUpdateInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 5041: [NR IPC] NrRcvSelfIpcHndlr_PrachStartInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 5081: [NR IPC] NrRcvSelfIpcHndlr_PostProcSysParamChangeInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 5121: [NR IPC] NrRcvSelfIpcHndlr_StrSettlingInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 5161: [NR IPC] PHY_L1C_PLL_JITTER_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 5208: [NR IPC] NrRcvSelfIpcHndlr_SibxSchedChange, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 5253: [NR IPC] NrRcvSelfIpcHndlr_PagingTimerCtrl, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 5295: [NR IPC] PHY_PHY_CS_CHANGE_CONFIG_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 5340: [NR IPC] NrRcvSelfIpcHndlr_PagingDrxCnfInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 5384: [NR IPC] PHY_PHY_OTHER_CDRX_TIME_REPORT, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
