Line 221: QuickSleep activation request (enableStatus:%d)
Line 233: QuickSleep deactivated (bitmap:0x%x), previous1(%d), previous2(%d)
Line 568: QS_CONDITION_DYNAMIC, disableConditionCount(%d), cond_dci/cond_crc/snr/dop(%04x), gap/csirs/mbsfn/crok/sf05(0x%05x), pseudoDci/dynamic/rstd/meas/sync(%05x)
Line 613: QSleep status changed: TTI/Status(%d/%d), (%d/%d)
Line 745: [AS] RSRP timer(%d,%d)
Line 773: [AS] U/L RSRP (%d,%d), diff(%d), status(%d), RxRsrpOffset(%d,%d), TAS_enb(%d)
Line 887: [AS] L/R RSRP (%d,%d), diff(%d), status(%d), RxRsrpOffset(%d,%d), meas_idx(%d)
Line 948: [4RxD] CC0 RSRP (%d,%d,%d,%d), diff(%d,%d), meas_idx(%d)
Line 1063: HST_STATE(%d), TEST_SIM(%d), div_enb(0x%x), 2RX mode
Line 1157: ONE_RX CHECK_signalQuality, CurMode(%d), SelectedMode(%d), disableConditions(%d), caOn/crcBad/lowSnr(%03x), filteredSinr(%d), ant_sw_txpwr_en(%d), maxpwr_tworx(%d)
Line 1175: IPC:RX MODE_CHANGE_NOTIFY (to ARM) - antennaMode(%d), caOn/crcBad/lowSnr(%03x), filteredSinr(%d)
Line 1202: [4RxD] Periodic 4Rx monitoring is skipped by DataInactiveStatus(%d) or MIMO Max(%d) or csi_static(%d)
Line 1214: [4RxD] Periodic 4Rx monitoring, AS_RX2_flag(%d), FourRx_RSRP_flag(%d), rxmode_bitmap(%d), FourRx_monitoring_trigger(%d)
Line 1221: [4RxD] div_enb(%d), div_num(%d), pActiveCC->num(%d)
Line 1415: [4RxD] sinr_path (%d,%d,%d,%d), sinr_2rx(%d,%d,%d)
Line 1416: [4RxD] CC%d scheduling rate (%d), rb_size_ratio(%d), isVoLTEcall(%d), ueCategory(%d), mimo_max(%d), rxmode_bitmap(%d)
Line 1523: [4RxD] 4X4MIMO is configured and waiting for changing to 4Rx, check(%d), check timer(%d)
Line 1531: [4RxD] 4X4MIMO is configured and waiting for changing to 4Rx, check(%d), check timer(%d)
Line 1671: [4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1676: [4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1697: [4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1702: [4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1721: [4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1726: [4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1738: [4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1743: [4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1792: [4RxD] 4RxD is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1797: [4RxD] 4RxD is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1829: IPC:RX MODE_CHANGE_NOTIFY (to ARM): %d, CC%d cur_rx_mode: %d
Line 1832: IPC:RX MODE_CHANGE_NOTIFY is skipped (to ARM), CC%d cur_rx_mode: %d
Line 1876: Best2RxSel: cck(%d), cand_bitmap(0x%x)
Line 1882: Best2RxSel: cck(%d), cand1,2,3(%d,%d,%d), rxc01,02,03(%d,%d,%d)
Line 1901: [4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1906: [4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1921: [4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1926: [4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1942: [4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1947: [4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
