Line 55: [INIT] L2LRX init start!
Line 97: [RX] L2LMACRX_L2_CONFIG_REQ
Line 102: L2LMACRX CONFIG TxReq[%d] LmacConfigCnt[%d]
Line 113: [TX] Sending L2_L2LMACRX_TX_REQ_T Fail
Line 121: [TX] Sending L2_L2LMACRX_CONFIG_CNF Fail
Line 125: [TX] L2_L2LMACRX_CONFIG_CNF
Line 137: [RX] L2LMACRX_L2_RESET_REQ : ResetCause[%d]
Line 150: [TX] Sending L2LRX_L2LMACRX_RESET_CNF Fail
Line 154: [TX] L2_L2LMACRX_RESET_CNF
Line 170: [RX] L2LMACRX_PHY_TX_TIMING_DIFF_IND
Line 188: [RX][MSG] L2LMACRX_L2LMACTX_DATA_LOOPBACK_IND
Line 199: L2LMACRX_L2TEST_RAR_IND_Handler start
Line 212: [RX] L2LMACRX_L2_TX_CNF TxReq[%d] LmacConfigCnt[%d] Result[%d]
Line 216: [RX][E] Unexpected L2LMACRX_L2_TX_CNF
Line 230: [TX] Sending L2_L2LMACRX_CONFIG_CNF Fail
Line 234: [TX] L2_L2LMACRX_CONFIG_CNF
