Line 226: [PDSCH_Preproc] Invalid DMRS configuration: dmrsType(%d), maxLength(%d)
Line 249: [PDSCH_Preproc] Invalid DCI format (0x%x)
Line 264: [PDSCH_Preproc] Discard DCI: RxAntNum(%d) is smaller than layer(%d) in DCI
Line 319: NrSpDchPreprocDev Discard Second DCI of Same HID in same Slot rx_time.aslot_idx (%d), dlCurTime.aslot_idx(%d)
Line 334: [PDSCH_Preproc] DCI of Same HID is parsing twice in continuos slot Harq_id (%d), prevNDI (%d), newNDI (%d), prevRV (%d), newRv (%d), prevAslotIdx (%d), newAslotIdx (%d)
Line 789: [PDSCH_Preproc] Undefined TimeD RA : pCch->pdcchSearchSpace(%d), MultiplexingPattern(%d), pCch->dci1_x.timeResourceAssign(%d)
Line 796: [PDSCH_Preproc] Undefined TimeD RA : pCch->pdcchSearchSpace(%d), MultiplexingPattern(%d), pCch->dci1_x.timeResourceAssign(%d)
Line 803: [PDSCH_Preproc] Invalid RNTI(%d), pdcchSearchSpace(%d)
Line 809: [PDSCH_Preproc] Invalid TimeD RA : pdschMappingType(%d), dmrsTypeAPosition(%d), S(%d), L(%d), S+L(%d)
Line 819: [PDSCH_Preproc] Invalid TimeD RA on F slot: nrofDownlinkSymbols(%d) < L(%d)
Line 825: [PDSCH_Preproc] NR_PDSCH_MAPPING_TYPE_B 
Line 937: [PDSCH_Preproc] Invalid FreqD RA : numPRBwithinBWP(%d)
Line 1079: [PDSCH_preproc] format(%d), pdcchSearchSpace(%d), rntiIdx(%d), detectedCoreset(%d)
Line 1121: [PDSCH_preproc] DCI 1_0 in CSS: RB_start(%d), L_RBs(%d), vrb2prb(%d), coresetZeroRbSize(%d), coresetStartRb(%d), pdcchSearchSpace(%d), rntiIdx(%d), detectedCoreset(%d)
Line 1146: [PDSCH_Preproc] Invalid FDRA : RA_type(%d), FDRA(%d), BWP_prbLength(%d), RB_start(%d), L_RBs(%d)
Line 1177: [PDSCH_Preproc] Invalid FreqD RA : pCch->ratype(%d)
Line 1234: [PDSCH_preproc] Vrb2PrbInterleaver ON : DCI(0x%x), SI_RNTI(%d), search space(%d), CoreSetIdx(%d), coresetZeroRbSize(%d), nr_demod_system_info(0x%x)
Line 1245: [PDSCH_preproc] Vrb2PrbInterleaver ON : invalid bwp_start_rb_index(%d)
Line 1258: [PDSCH_preproc] Vrb2PrbInterleaver ON : DCI(0x%x), search space(%d), coresetZeroRbSize(%d), NrSpBandwidthPartDLInfo.startPrb(%d), coresetStartRb(%d), first_prg_offset(%d)
Line 1293: [PDSCH_preproc] Vrb2PrbInterleaver Invalid: pdsch_start_symbol_index(%d), pdsch_symbol_num(%d), interleaving_size(%d), interleaving_shift(%d), dl_rb_num(%d)
Line 1405: [PDSCH_preproc] mcs_C_RNTI.NR_MCFG_IE_CONFIG_FLAG(%d), pdschCfgMcsTable.NR_MCFG_IE_CONFIG_FLAG(%d), pdschCfgMcsTable.value(%d), rntiIdx(%d), pdcchSearchSpace(%d), mcsTableIdx(%d)
Line 1422: [PDSCH_preproc] mcs_C_RNTI.NR_MCFG_IE_CONFIG_FLAG(%d), rntiIdx(%d), mcsTableIdx(%d)
Line 1439: [PDSCH_preproc] spsCfgMcsTable.NR_MCFG_IE_CONFIG_FLAG(%d), pdschCfgMcsTable.NR_MCFG_IE_CONFIG_FLAG(%d), pdschCfgMcsTable.value(%d), format(%d), rntiIdx(%d), using SPS-config(%d), mcsTableIdx(%d)
Line 1459: [PDSCH_preproc] spsCfgMcsTable.NR_MCFG_IE_CONFIG_FLAG(%d), spsCfgMcsTable.value(%d), rntiIdx(%d), using SPS-config(%d), mcsTableIdx(%d)
Line 1480: [PDSCH_Preproc] Invalid MCS on P_RNTI/RA_RNTI/SI_RNTI (Qm>2): rnti(%d), modOrder(%d)
Line 1550: [PDSCH_Preproc] Invalid CalcDmrsRE dmrsCfgType(%d)
Line 1628: [PDSCH_Preproc] Invalid DmrsRE NR_PDSCH_MAPPING_TYPE_B : durationInSymbols(%d), cpType(%d)
Line 1651: [PDSCH_Preproc] Invalid CalcDmrsRE dmrsAddPos(%d) for len2
Line 1663: [PDSCH_Preproc] Invalid CalcDmrsRE dmrsAddPos(%d) for len2
Line 1672: [PDSCH_Preproc] Invalid CalcDmrsRE dlDmrsMaxLength(%d), dmrsMappingType(%d)
Line 1679: [PDSCH_Preproc] Invalid CalcDmrsRE rntiIdx(%d)
Line 1833: [PDSCH_Preproc] Invalid TB_scaling field(%d)
Line 1949: [PDSCH_Preproc] Invalid Trbk calculation: newTx(%d), tbs(%d), tbRst(%d)
Line 1964: [PDSCH_Preproc] Invalid Trbk calculation: newTx(%d), mcsTable(%d), Imcs(%d)
Line 1973: [PDSCH_Preproc] Invalid Trbk calculation: mcsTable(%d), Imcs(%d)
Line 1979: [PDSCH_Preproc] different Trbk size with previous one tbs(%d), prevTbs(%d), newTx(0x%08x)
Line 1989: [PDSCH_Preproc] Invalid TBS exceeding 2976 bits with SI_RNTI(%d) TBS(%d)
Line 2106: [PDSCH_Preproc] TBS_LBRM(%d), maxCodeBlockNum(%d), layer_LBRM(%d), maxPRBacrossBWPs(%d), freqRange(%d), maxMimoLayer.NR_MCFG_IE_CONFIG_FLAG(%d), maxMimoLayer.value(%d), pdschCfgMcsTable.NR_MCFG_IE_CONFIG_FLAG(%d), pdschCfgMcsTable.value(%d)
Line 2299: [PDSCH_Preproc] Invalid channel : decSkip(0x%x)
Line 2331: [PDSCH_Preproc] Set newTx NR_NEW_RXMODE_MISMATCH_MASK : previous decSkip(0x%x), harqProcNum(%d), newTx(%x)
Line 2503: [PDSCH_Preproc] NrSpSchDec(cc_idx=%d) ack2Nack harqProcNum:%d, newTx:0x%08x, tbRslt:0x%08x, decSkip:0x%08x, pdschAck2NackCnt:%d
Line 2512: [PDSCH_Preproc] NrSpSchDec(cc_idx=%d) pdschResidualErrCnt harqProcNum:%d, newTx:0x%08x, tbRslt:0x%08x, decSkip:0x%08x, pdschResidualErrCnt:%d
