Line 287: [FBRX] POW_MEAS_CFG0 %x, POW_MEAS_CFG1 %x
Line 319: [FBRX] DCR_ACCUM_VALUE0  %x
Line 320: [FBRX] FBRX_AGC0 %x, FBRX_DCR0 %x, temp_FIRCONTROLSELREQ %x
Line 370: [FBRX][ON] FBRX_AGC0 0x%X, FBRX_DCR0 0x%X, FIRCONTROLSELREQ 0x%X, RFD_2G_FBRX_GSMRFD_SW_RESET 0x%x, 2G_PATH_SEL_MSB 0x%X, DCR_ACCUM_VALUE0 0x%X 
Line 403: [FBRX][OFF] DCR_ACCUM_VALUE0  %x, POW_MEAS_VALUE0 %x
