Line 177: [DCCCH] NR_DC_CCH_RELEASE !!
Line 208: [DCCCH] Reconfiguration is ongoing. Do not set CCH.bk_cch_reconfig_flag(%d) 
Line 272: [DCCCH] Reconfiguration is ongoing. Do not set CCH.bk_cch_reconfig_flag(%d) 
Line 420: [DCCCH] REG: nr_coreset_on - (0x%X), monitoringCoresetNum(%d),  MonitoringNum_this_slot0123(1/1/1/1)(%d)
Line 465: [DCCCH]hashY ssId(%d) 0[%d]1[%d]2[%d]3[%d]4[%d]5[%d]
Line 502: [DCCCH] ERROR: controlResourceSetId(%d)
Line 526: [DCCCH] ERROR: controlResourceSetId(%d)
Line 531: [DCCCH][SetCInitvalue] presentflag(common/dedi)(%d)/(%d), css_yinit(0x%x), uss_yinit(0x%x/0x%x/0x%x/0x%x)
Line 666: [DCCCH] CalAntPortsFail! Check MappingType(%d),transformPrecoder(%d), maxLength(%d) 
Line 669: [DCCCH] CalAntPortSize(%d), MappingType(%d),transformPrecoder(%d), dmrs_TypeUL(%d), maxLength(%d) 
Line 792: [DCCCH]CalDCILength,lengthofFMT0/1/2/3(2/2/2/2)(%d),carrierInd(%d),FDRAULT0/T1/InitUL(2/2/2)(%d),fmt01BWP/UL_SUL/TDRA/frhop/DLaIdx1/DLaIdx2/TPC/SRS(%d), fmt01PrecInfo/antPorts/CSI/cbg/asso_PTRS_DMRS/beta/DmrsSeq/UL_SCH_indi(%d),FDRADLT0/T1/C0_Init(2/2/2)(%d), fmt11BWP/TDRA/vrb2prb/prbB/rateM/zpCsi/DLaIdx/Pdsch2HarqF(%d),antPorts/transC/cbgT/cbgFl/DmrsS(%d), NrCaState(%d)
Line 870: [DCCCH]CalFAMetric TH_pm01/02(4/4)(%d), TH_pm03/04(4/4)(%d), TH_pm11/12(4/4)(%d), TH_pm13/14(4/4)(%d), TH_pm21/22(4/4)(%d), TH_pm23/24(4/4)(%d),TH_pm31/32(4/4)(%d), TH_pm33/34(4/4)(%d)
Line 881: [DCCCH]CalFAMetric TH_ser01/02(4/4)(%d), TH_ser03/04(4/4)(%d), TH_ser11/12(4/4)(%d), TH_ser13/14(4/4)(%d), TH_ser21/22(4/4)(%d), TH_ser23/24(4/4)(%d),TH_ser31/32(4/4)(%d), TH_ser33/34(4/4)(%d)
Line 962: [DCCCH][CalRAsize]nRB(%d), typeRA (%d) raSize(%d), rbgConfig(%d), LinkType(%d)
Line 993: (F)Invalid Periodicity(%d)
Line 1056: Invalid RRC param! Skip CSS: coresetId(%d), ssId(%d), rntiBitmap(0x%X)
Line 1066: [DCCCH]SetSearchSpaceInfo: ssId(%d), m_next_slot_idx(%d), m_next_slot_idx_frame(%d), monitoringSlotPeriodicity(%d), Offset(%d), duration(%d), rntiBitmap(0x%X),mon_rntiBitmap_SS(0x%X),ssType/IsPdcchMonitoringRequired(1/1)(%d), isstartCCEcaldone(%d)
Line 1121: (F)Invalid dci_Formats(%d)
Line 1124: (F)Invalid ssType(%d)
Line 1182: (F)INVALID search space info: ssId(%d) m_CcIdx(%d)
Line 1307: (F)[DCCCH][SetCoresetInfo] Invalid coresetId(%d)
Line 1595: (F)[DCCCH][ClearCoresetInfo] Invalid Param mode(%d) coresetId(%d)
Line 1699: (F)[DCCCH][SetSearchSpaceCandiBmp] Invalid Param: m_CcIdx(%d)/coresetId(%d)
Line 1733: (F)[DCCCH][SetSearchSpaceCandiBmp] Invalid Param: num_of_al1_scce(%d)
Line 1748: (F)[DCCCH][SetSearchSpaceCandiBmp] Invalid Param: num_of_al2_scce(%d)
Line 1763: (F)[DCCCH][SetSearchSpaceCandiBmp] Invalid Param: num_of_al4_scce(%d)
Line 1778: (F)[DCCCH][SetSearchSpaceCandiBmp] Invalid Param: num_of_al8_scce(%d)
Line 1793: (F)[DCCCH][SetSearchSpaceCandiBmp] Invalid Param: num_of_al16_scce(%d)
Line 2041: [DCCCH] AntPortsFail! dmrs_UplinkForPusch_presentflag(%d), 
