Line 97: [DCCCH] ERROR: controlResourceSetId(%d)
Line 122: [DCCCH] ERROR: controlResourceSetId(%d)
Line 128: [DCCCH][SetCInitvalue] presentflag(common/dedi)(%d)/(%d), css_yinit(0x%x), uss_yinit(0x%x/0x%x/0x%x/0x%x)
Line 162: [DCCCH][CalNumCCE] Coreset Id is mismatched! present_flag(0x%x), coresetId(%d), Indicated CoresetId(%d)
Line 175: [DCCCH][CalNumCCE] ssId(%d) coresetId (%d) coresetlength(%d), assigned_cchrbnum(%d), m_NumCCE(%d) totalCCHRE(%d) NumREperCCE(%d)
Line 586: [DCCCH][SetCoresetInfoforDD]coresetId(%d), ra_info(0x%x), ra_info1(0x%x), first_prg_offset(%d), bundle_info(0x%x)
Line 657: [BACKGROUND TASK] NrDcDevBgTask_CchReconfig: done(%d)
