Line 103: fachControllerArray[0] == NULL
Line 282: tphy_CFachResources insttance mem allocation failed
Line 325: Warning: FachConfigMsg configMsg->payload.sccpchInfo.CommonTimeSlotInfo.TFCI_Coding out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 340: Warning: FachConfigMsg configMsg->payload.sccpchInfo.CommonTimeSlotInfo.RepPeriod out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 353: Warning: FachConfigMsg configMsg->payload.sccpchInfo.CommonTimeSlotInfo.InterleavingMode out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 366: Warning: FachConfigMsg configMsg->payload.sccpchInfo.IndividualTimeSlotInfo.timeslotNumber out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 380: Warning: FachConfigMsg configMsg->payload.sccpchInfo.IndividualTimeSlotInfo.MidambleShiftandBurst.MidambleAllocationMode out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 393: Warning: FachConfigMsg configMsg->payload.sccpchInfo.IndividualTimeSlotInfo.MidambleShiftandBurst.MidambleConfiguration out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 408: Warning: FachConfigMsg configMsg->payload.sccpchInfo.IndividualTimeSlotInfo.MidambleShiftandBurst.MidambleShift out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 424: Warning: FachConfigMsg configMsg->payload.numOfDlCtfc out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 441: Warning: FachConfigMsg configMsg->payload.dlCtfcArray[i] out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 456: Warning: FachConfigMsg configMsg->payload.numOfFach out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 476: Warning: FachConfigMsg configMsg->payload.fachInfoArray[i].dlTrCh.trChType out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 491: Warning: FachConfigMsg configMsg->payload.fachInfoArray[i].dlTrCh.semiStaticInfo.tti out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 504: Warning: FachConfigMsg configMsg->payload.fachInfoArray[i].dlTrCh.semiStaticInfo.channelCoding out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 517: Warning: FachConfigMsg configMsg->payload.fachInfoArray[i].dlTrCh.semiStaticInfo.rateMatchingArgument out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 530: Warning: FachConfigMsg configMsg->payload.fachInfoArray[i].dlTrCh.semiStaticInfo.crcSize out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 543: Warning: FachConfigMsg configMsg->payload.fachInfoArray[i].dlTrCh.semiStaticInfo.codingRate out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 558: Warning: FachConfigMsg configMsg->payload.fachInfoArray[i].dlTrCh.dynamicInfo.numOfTfTableEntries out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 575: Warning: FachConfigMsg configMsg->payload.fachInfoArray[i].dlTrCh.dynamicInfo.tfTableEntryArray[j].numOTblocks out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 588: Warning: FachConfigMsg configMsg->payload.fachInfoArray[i].dlTrCh.dynamicInfo.tfTableEntryArray[j].tBlockSize out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 610: Warning: FachConfigMsg configMsg->payload.pchInfo.dlTrCh.semiStaticInfo.tti out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 623: Warning: FachConfigMsg configMsg->payload.pchInfo.dlTrCh.semiStaticInfo.channelCoding out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 636: Warning: FachConfigMsg configMsg->payload.pchInfo.dlTrCh.semiStaticInfo.rateMatchingArgument out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 649: Warning: FachConfigMsg configMsg->payload.pchInfo.dlTrCh.semiStaticInfo.crcSize out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 662: Warning: FachConfigMsg configMsg->payload.pchInfo.dlTrCh.semiStaticInfo.codingRate out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 678: Warning: FachConfigMsg configMsg->payload.fachOccasionInfo.fachOccasionCycleLengthCoef out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
