Line 99: [NR][TTI_DBDEV][INIT] m_CcIdx(%d), system_info_systime(0x%X), SCS(DL/UL)=(%d/%d)
Line 135: [NR][TTI_DBDEV][CFG] Force holding (FR2): %d
Line 139: [NR][TTI_DBDEV][CFG] SCS(PREV/NEXT)(%d/%d) FLG_HOLDING/BYSCS(%d/%d)
Line 160: [NR][TTI_DBDEV][CFG] Update CFG: SCS(DL/UL)(%d/%d) CPTYPE(DL/UL)(%d/%d) status_reg/isForceHoldingTrue/Flag_holding/flag_holdingbyscs(%d/%d/%d/%d)
Line 217: [NR][TTI_DBDEV][CFG] TtiSiListInfo is updated : sibxState(%d), numSiList(%d)
Line 240: [NR][TTI_DBDEV][CFG] Update default CFG: m_CcIdx:%d  prvFrontCcIdx(%d) frontCcIdx(%d) rf_idx(%d), rf_idx_div(%d), ue_ant_num(%d), scs_ssb(%d) scs_default(%d) flag_wakeup/holding_skip(%d)
Line 473: [NR IPC] L1C_PHY_MIB_ACQ_CNF, BM_SrcCcForCnfMsg(%d), ipc(%d), cmd(%d) numRb(%d) rbOffset(%d)
Line 488: [NR IPC] L1C_PHY_SYS_PARAM_CHG_CNF, BM_SrcCcForCnfMsg(%d), ipc(%d)
Line 515: [NR IPC] L1C_PHY_LCPU_INIT_CNF, BM_SrcCcForCnfMsg(%d)
Line 531: [NR IPC] PHY_PHY_LCPU_RELEASE_READY, BM_SrcCcForCnfMsg(%d), ipc(%d)
Line 545: [NR IPC] L1C_PHY_DRX_WAKEUP_INIT_CNF, BM_SrcCcForCnfMsg(%d), ipc(%d)
Line 559: [NR IPC] L1C_PHY_RESTORE_PCELL_PHY_CONFIG_CNF, BM_SrcCcForCnfMsg(%d), ipc(%d)
Line 612: [NR][TTI_DBDEV][EVT] state change counter expired: event(%d) flag_event_statechange(0x%X) DC(0x%X)DF(0x%X)
Line 685: [NR][TTI_DBDEV][State] Hoding State change: CNT(%d)
Line 709: [NR][TTI_DBDEV][State] Hoding by SCS change State change: CNT(%d)
Line 767: (F) Error in StateChange: cause(%d) current_state(%d)
Line 800: (F)INVALID event(%d)
Line 819: (F)INVALID event(%d)
Line 839: (F)INVALID event(%d)
Line 858: (F)INVALID event(%d)
Line 929: (F)INVALID STATE!! (%d)
