Line 53: [RF SM] SM_Init !!
Line 70: [RF SM] %s SM has been opened! handle[%d]
Line 75: [RF SM] Warning : %s SM is unused! Error(0x%x)
Line 101: [RF SM] %s SM Boot Up is OK :: handler %d!!
Line 105: [RF SM] %s SM Boot Up is failed!!(0x%x)
Line 123: [RF SM] %s SM Off is OK :: handler %d!!
Line 127: [RF SM] %s SM Off is failed!!(0x%x)
Line 352: [RF SM] RF_SM_Control error(0x%x) 
Line 430: [RF SM] SM get Setting data error(0x%x) 
Line 462: [RF SM] SM Check 2G APT Support error (0x%x) 
Line 476: [RF SM] SM_Check_Status (cc : %d), (level : %d)
Line 482: [RF SM] SM Check status error (0x%x) 
Line 500: [RF SM] SM Get ID error (0x%x) 
Line 520: [RF SM] SM Get MIPI Info error (0x%x) 
Line 539: [RF SM] SM Get Revision ID error (0x%x) 
Line 558: [RF SM] SM Get Module Type error (0x%x) 
Line 577: [RF SM] SM Get current voltage error (0x%x) 
Line 599: [RF SM] SM Get voltage from MIPI error (0x%x) 
Line 622: [RF SM] SM Compensate gain error (0x%x) 
Line 640: [RF SM] RF_SM_Set_OCP( error (0x%x) 
Line 659: [RF SM] RF_SM_Set_Rat_Mode( error (0x%x) 
Line 677: [RF SM] RF_SM_Set_Out_Port( error (0x%x) 
Line 697: [RF SM] RF_SM_Set_Small_Buck( error (0x%x) 
Line 714: [RF SM] RF_SM_Change_USID( error (0x%x) 
Line 733: [RF SM] RF_SM_Get_ET_DAC_COMP_INFO( error (0x%x) 
