Line 92: ###[NR_IRAT_PROC] SetActiveRatInfo : IsActiveRat(%d), InitType(%d), RatConfigType(%d), ChipVersion(0x%x)
Line 127: ###[NR_IRAT_PROC][WARNING] SetActiveRatInfo:: Undefined ActiveRatConfigType(%d)
Line 146: ###[NR_IRAT_PROC] SetUpActiveRatInfoProc:: InitType(%d)
Line 174: ###[NR_IRAT_PROC] SetDownActiveRatInfoProc, LcpuRel: InitType(%d)
Line 201: ###[NR_IRAT_PROC] cc_idx(0x%x), processor_idx(0x%05x), hw_demod_idx(0x%05x)
Line 209: ###[NR_IRAT_PROC] LcpuState check : core(%d), state(%d), demod(%d)
Line 218: ###[NR_IRAT_PROC] SendLcpuInitIpc:: DemodCcBitMap(0x%08x)
Line 258: ###[NR_IRAT_PROC] Lcpu coreId(%d) is in the process of initialization, demod(%d), cnt(%d)
Line 270: ###[NR_IRAT_PROC] SendLcpuReleaseIpc:: DemodCcBitMap(0x%08x)
Line 323: ###[NR_IRAT_PROC][ProcTime] SetSysValidEnable: SetActiveRatDone (%d)
Line 329: ###[NR_WAKEUP][WARNING] SysValidConfigProc: SysValidNrCmd isn't running
Line 354: ###[NR_IRAT_PROC][WARNING] Unexpected TimeCompenMode(%d)
