Line 63: == Task(%d) ==
Line 82: ChangeAffinity	ERROR!! : Affinity over MAXCORE(change affinity %d==>%d)
Line 82: ChangeAffinity	ERROR!! : Affinity over MAXCORE(change affinity %d==>%d)
Line 82: ChangeAffinity	ERROR!! : Affinity over MAXCORE(change affinity %d==>%d)
Line 82: ChangeAffinity	ERROR!! : Affinity over MAXCORE(change affinity %d==>%d)
Line 82: ChangeAffinity	ERROR!! : Affinity over MAXCORE(change affinity %d==>%d)
Line 85: 	idx(%d) : Affinity(%d)
Line 85: 	idx(%d) : Affinity(%d)
Line 85: 	idx(%d) : Affinity(%d)
Line 85: 	idx(%d) : Affinity(%d)
Line 85: 	idx(%d) : Affinity(%d)
