Line 128:  NORMAL Initialisation of <GmmCellIndicationt> 
Line 167:  GSM to UMTS Initialisation of <GmmCellIndicationt> 
Line 173:  UMTS to GSM Initialisation of <GmmCellIndicationt> 
Line 180:  Unknown Initialisation Type (%x) in mm_InitGmmCellIndication 
Line 210: UMTS Moved from No PS service to In PS serviec
Line 225: UMTS Current and Sim RAI are same ChangeinRai : False
Line 229: UMTS Current and Sim RAI are different ChangeinRai : TRUE
Line 331: CnCommonNasInfo Absent !!!! PLMN Changed without LAC changing?! Msg ignored in  mm_UpdateAndProcessGmmCellData 
Line 366: SIB derived CN information does not include PS domain specific SI (i.e. RAC and network mode)...assuming PS domain currently unavailable in selected cell
Line 379: Network sourced CN information does not include PS domain specific SI (i.e. RAC and network mode)...assuming PS domain currently unavailable in selected cell
Line 436: PLMN identity not included - using previously stored value
Line 461: CN Common SI (LAC) not included - using previously stored value
Line 466: SIB derived CN information does not include CN common GSM-MAP NAS SI (i.e. LAC)...
Line 490: PLMN identity not included - using previously stored value
Line 513: CN Common SI (LAC) not included - using previously stored value
Line 551:  Setting GMM_RAI_CHANGED_FLG_...
Line 618:  URRC_MM_NO_CELL_IND....
Line 655: Moved from PS no service to PS in Service
Line 662: GSM Current and Sim RAI are same ChangeinRai : False
Line 666: GSM Current and Sim RAI are different ChangeinRai : TRUE
Line 695: mm_GmmCellData.CellChange is set to FALSE.
Line 700: mm_GmmCellData.CellChange is set to TRUE.
Line 721: NwExtUtbf= %d
Line 752: EncodedSizeinBits -> %d 
Line 753: Access Technology changed...
Line 757: Access Technology did not change...
Line 775:  CR 98 :Set : mm_SetGmmFlag....
Line 781:  CR 98 :Clear : mm_SetGmmFlag....
Line 815:  ....cell does not support PS.
Line 821: ....ignored as DataResumption == GRR_GMM_NO_RESUMPTION.
Line 838:  GRR_MM_NO_CELL_IND....
Line 864: Because of Power off detach or PS detach PS off and  GMM Deregistered we skip GmmCellData process.
Line 915:  ERROR: unknown TypMsg 0x%02X in MM_UMTS_RAT_MODE 
Line 960:  ERROR: unknown TypMsg 0x%X in MM_GSM_RAT_MODE 
Line 983: discard GMM SM EST REQ
Line 1011: SameRrConnexFailAction = %d, ProcessCellInfo =%d 
Line 1038: Current serving cell is not supportting PS services(or barred), GMM_GPRS_ATTACH_FLG = FALSE
Line 1042: LAI is not changed, so send Registration ind to NS for PS barred status
Line 1047: NO CELL IND, keep GMM_GPRS_ATTACH_FLG == TRUE
Line 1053: Current serving cell is supporting PS services and UE GMM REG/UPDATED, GMM_GPRS_ATTACH_FLG = TRUE
Line 1057: Send reg status ind(PS not supported -> supported) on recovery to prev reg RAI
Line 1109: GMM shall process new cell details now...
Line 1115: GMM shall process new Unit Data Ind details now...
Line 1122: NMO-1 GMM shall process new cell details now. Received GSM CELL IND ..
Line 1144: GMM shall not process new cell details now...shall process on completion of MM location updating procedure
Line 1156: GMM shall not process new cell details...CSFB call about to initiated
Line 1164: In MM_WAIT_FOR_RR_CON_LOC_UPD state LAI changed, After Cell indication LAU should be initiated..GMM shall not process new cell details now till Perform LAU procedure
Line 1179: GMM shall not process new cell details...URRC_MM_CELL_IND received in while a PS signalling connection exists
Line 1186: GMM shall process new cell details now...
Line 1213: GMM processing of new cell details in %s in mm_ProcessGmmCellInformation
Line 1273: Attempting to go back to GMM State before Supension...mm_GmmStateBeforeSuspension = %s
Line 1279: Abort any ongoing GMM procedure and later Trigger  GPRS detach procedure in GMM state= %s
Line 1324: GMM state was GMM_SERVICE_REQUEST_INITIATED but have moved to GSM RAT, reverting to GMM_REGISTERED
Line 1373: ERROR: Invalid mm_GmmState....
Line 1440: CLEARING Gmm Regist status Cause
Line 1445: NOT CLEARING Gmm Regist status Cause, Cause %d
Line 1553:  Need to do GPRS Attach UE is in NMO1 So try Combined Attach to establish the Gs association in the MSC/VLR.
Line 1562: GMM is in LIMITED and PS domain barred... So nothing done here... 
Line 1576: RAI Changed
Line 1592: Cell Changed & Must Retry in New Cell
Line 1599: GMM_T3302 had expired while GMM was suspended
Line 1612: Cell changed and Att req action is GMM_NO_ATT_ACTION under attemping to attach / dereg state, need to do attach again.
Line 1662: GMM_NO_IMSI -> Should Never Have Got Here !!! 
Line 1670: ERROR: Unexpected mm_GmmServiceState....
Line 1683: GPRS attach (re)initiation...
Line 1711: CS call had been attempted, retry now...
Line 1765: Change of Cell into New Routing Area....
Line 1776: New RAI before Est Cnf has been received. Must Break RR Con and start Again. Please Wait...
Line 1793: GPRS Attach Procedure Following Intersystem Change Between Cells Belonging to the Same RA....
Line 1808: Change of cell within the same RA => Perform Cell Update [24.008]-4.7.3.1.5.e....
Line 1823: Access barred Due to Access Class Control....
Line 1835: Must Break RR Con. .
Line 1848: Lower Layer Failure....
Line 1866: Loss of coverage during Signalling, end the signalling
Line 1939: GMM_REGISTERED.mm_GmmCellData.NetworkService = %d 
Line 1972: ISR is activated but RAI is changed after L2U Rat Change. RRC Est Cause is set to InterRAT Cell Reselection.
Line 2001: RAU recovery procedure is performed..
Line 2034: RAU recovery procedure is performed..
Line 2046: RAT Change to UMTS Detected -> GSM to UMTS Intersystem Change Between Cells Belonging to Same RA...GPRS Functional State was %s on Intersystem Change....
Line 2050:  => Initiate RAU Procedure Immediately....
Line 2063: Normal RAU Procedure on Intersystem Handover from GSM to UMTS during CS Connection....
Line 2072: RAU Procedure Not Required Until Uplink Signalling or Data Transmission. [24.008]-4.7.1.7 (b)...
Line 2079: RAT Change to GSM Failed, Now Back in UMTS again -> MS in Same Access Network as when last sent user data or signalling, normal procedures shall be followed.....
Line 2100: mm_RauForGprsResumeReEntryFlag is RESET as RauNeeded is Set....
Line 2113: RAU Procedure Initiation Required for GPRS Resumption in the Network....DataResumption=%d, mm_RauForGprsResumeReEntryFlag=%d
Line 2125: RAU Procedure Initiation as GMM_T3302 Expired in GMM_SUSPENDED state....
Line 2133: RAU recovery procedure is performed..
Line 2143: Cell update procedure will be blocked during Manual PLMN searching.
Line 2150: Change of Cell in Same Routing Area....
Line 2167: RAT Change to GSM Detected -> UMTS to GSM Intersystem Change Between Cells Belonging to Same RA....PMM functional state was %s on intersystem change....
Line 2171:  => Initiate RAU Procedure Immediately....
Line 2180: RAU procedure not required until uplink signalling or data transmission. [24.008]-4.7.1.7 (b)...
Line 2199:  => Initiate RAU Procedure due to MM_AUTO_PLACEMENT_IN_QUEUE....
Line 2209: RAT Change to UMTS Failed, Now Back in GSM again -> MS in same access network as when last sent user data or signalling, normal procedures shall be followed.....
Line 2266: change of cell into new routing area....
Line 2286: change of cell in same routing area having received cause 'Retry upon entry into a new cell'....
Line 2305: GMM CELL DATA RAI != SIM RAI and No timer for retrying RAU, Here RAU is necessary. 
Line 2313: RAU procedure as GMM_T3302 expired in GMM_SUSPENDED state...
Line 2326: RAU procedure should be triggered due to NMO change (not periodic)
Line 2373: change of cell into new routing area....
Line 2384: RAU needed flag is set
Line 2422: access no longer barred....
Line 2475: Change of Cell into New Routing Area....
Line 2491: Network mode change during GPRS detach procedure for CS services
Line 2508: IMSI Detach Procedure After RAU Procedure Following Intersystem Change Between Cells Belonging to the Same RA....
Line 2521: Change of Cell in Same Routing Area....
Line 2533: Lower Layer Failure....
Line 2618:  ERROR: mm_GmmState and mm_GmmServiceState incompatible! 
Line 2633: MO/MT Call was attempted in NMO1. This should be stopped before RAU Procedure ....
Line 2662: RAU will be pended while MO/MT call is in progress....
Line 2680: Initiating RAU Procedure .... after WFRAU timer is expired
Line 2688: Initiating RAU Procedure .... if Quick Rollback is over
Line 2695:  Quick rollback is in progress, so processing MM cell ind further, if QRB for G2L is failed 
Line 2701: Initiating RAU Procedure ....
Line 2718: RAU procedure not initiated due to access class barred....
Line 2735: SM Informed of 'Lost' Radio Coverage....
Line 2740: SM Informed of Regained Radio Coverage....
Line 2781: SM Informed of 'Lost' Radio Coverage....
Line 2787: SM Informed of Regained Radio Coverage....
Line 2793: Resumed Again on UMTS Rat So no need to Do Anything 
Line 2831: CS call had been attempted, retry now...
Line 2864: CS call had been attempted, retry now...
Line 2914: Change of Cell into New Routing Area. Starting RAU...
Line 2923: New RAI before Est Cnf has been received. Must Break RR Con and start Again. Please Wait...
Line 2946: RAT Change Detected During RAU Procedure...RAU Procedure Following Intersystem Change Between Cells Belonging to the Same RA
Line 2960: Change of Cell in Same Routing Area....
Line 2972: Access Barred Due to Access Class Control....
Line 2984: Must Break RR Con. .
Line 3009: Gmm cell data. network service exceeds the limit
Line 3033: SM informed of 'Lost' Radio Coverage....
Line 3072: Change of Cell into New Routing Area....
Line 3080: Change of RAC Detected, during Detach for PS Switching
Line 3124: New RAI before Est Cnf has been received. Must Break RR Con and start Again. Please Wait...
Line 3146: RAT Change Detected During Detach -> RAU Procedure then Normal GPRS Detach Following Intersystem Change Between Cells Belonging to the Same RA....
Line 3167: change of cell within the same RA....
Line 3212: .... lower layer failure
Line 3249: Change of cell into new RA...
Line 3283: RRC requested to 'release' PS signalling connection before RAU procedure initiation...
Line 3293: PMM_CONNECTED: RRC requested to 'release' PS signalling connection before RAU procedure initiation...%d
Line 3300: RAU procedure 'interupts' service request procedure...
Line 3362: CS call had been attempted, retry now...
Line 3382: Loss of coverage during service request procedure...
Line 3394: mm_GmmCellIndDb[MmStackId].mm_GmmCellData.NetworkService exceeds the limit
Line 3404: SM informed of 'lost' radio coverage....
Line 3421: RRC requested to 'release' PS signalling connection Because Lost Coverage Before Moving to Conn Mode
Line 3460: GCF Mode is Enabled
Line 3463: In UMTS RAT, PMM connected Mode and Network mode 1
Line 3467: Current and SIM data PLMNs are not same and PLMN Found in Equivalent Plmn List
Line 3470: LA and RA of the SIM and the current cell data are same.
Line 3640: GRR_GMM_SUSPEND_IND received in state %s 
Line 3687: mm_EncodedDrxParam = 0x%02X 0x%02X
Line 3851:  Invalid NewState in mm_SetGmmStateBeforeSuspension 
Line 4127:  Re-setting GMM CellData 
Line 4147:  Setting GMM CellData for Recovery 
Line 4166:  Restore Gmm CellData for Recovery 
Line 4196:  GMM Cell Data RAC -> 0x%02X 
Line 4215: mm_GmmCellData.Rai                 = %02X %02X %02X %02X %02X %02X 
Line 4228: mm_GmmCellData.NetworkMode         = %s
Line 4240: ---------------------Current GMM cell details---------------------
Line 4243:  RAT mode -> %s
Line 4248:  Access tech type -> %s
Line 4252:  RAT mode -> %s,          Network service -> %s
Line 4257:  Forbidden PLMN
Line 4263:  Forbidden PLMN for GPRS services
Line 4269:  Forbidden LA
Line 4275:  Forbidden LA for roaming
Line 4281:  PLMN selection has been started by MM
Line 4285:  Network access -> %s,         Network mode -> %s 
Line 4291:  RAI -> %02X %02X %02X %02X %02X %02X,          Cell identity -> %07X
Line 4296: Cell change -> %s, Data resumption -> %s
Line 4301:  Cell change -> %s
Line 4314: ---------------------Previous GMM cell details---------------------
Line 4317:  RAT mode -> %s,          Network mode -> %s
Line 4322:  Access tech type -> %s
Line 4329:  RAI -> %02X %02X %02X %02X %02X %02X,          Cell identity -> %07X
Line 4394: Even though Band is changed in NMO1, we don't have anything to send again! 
Line 4438: Wrong Action =%d 
