Line 235: ProtDisc: %d
Line 262: LLGMM_TRIGGER_IND received in GMM_SUSPENDED state...
Line 264: ...processing according to pre-suspension state of %s
Line 298: No specific actions on transmission of %s...
Line 306: LLGMM_TRIGGER_IND containing unmatched PduId in GMM_DEREGISTERED
Line 339: READY timer is deactivated and shall run without expiry
Line 346: Network has forced MS to STANDBY state -> READY timer not started
Line 360: PDP Context Status is %d %d
Line 370: READY timer (re)started
Line 417: No specific actions on transmission failure of %s...
Line 425: LLGMM_STATUS_IND containing unmatched PduId in GMM_DEREGISTERED...
Line 473: LLGMM_STATUS_IND containing unmatched PduId, GPRS attach fail actions not performed...
Line 495: Lower layer failure during GPRS detach procedure for IMSI only...
Line 507: LLGMM_STATUS_IND indicating GMM PDU transmission failure before DETACH_REQUEST transmission attempt, no actions performed...
Line 513: LLGMM_STATUS_IND containing unmatched PduId or corresponds to a non-GMM SAPI-1 PDU, no actions performed...
Line 546: Reject UE Pending Req because RAU Failed due to Lower Layer Failure.
Line 572: LLGMM_STATUS_IND containing unmatched PduId, RAU fail actions not performed...
Line 592: Lower layer failure during GPRS detach procedure...
Line 637: LLGMM_STATUS_IND indicating GMM PDU transmission failure before DETACH_REQUEST transmission attempt, no actions performed...
Line 643: LLGMM_STATUS_IND containing unmatched PduId, no actions performed...
Line 668: Cause = %s
Line 696: LLGMM_STATUS_IND received for authenticaiton or identity message, do not abort the complete procedure
Line 724: LLGMM_STATUS_IND received in GMM_SUSPENDED state...
Line 727: ...processing according to pre-suspension state of %s
Line 756: Perform TbfRelAction, MM_COORD_TBF_REL_ACTION
Line 775: Perform TbfRelAction, MM_COORD_TBF_REL_ACTION
Line 843: GPRS attach / RAU procedure completed, start DRX and resume LLC...
Line 871: Received ACK For RAU/ATTACH COMPLETE So Stop Timer and Set the State
Line 932: Performing actions following DETACH_REQUEST transmission (or failure)...
Line 962: Indication of GPRS detach procedure completion delayed until reception of RLC_GMM_SAPI_ONE_TX_COMPLETE...
Line 995: GMM_DETACH_TRY_TIMER not running on LLC indication of DETACH_REQUEST transmission, no actions performed...
Line 1014: Performing actions following DETACH_ACCEPT transmission (or failure)...
Line 1069: SAPI-1 Tx table entry %d has been reserved with PduId %04X...
Line 1074: ...for transmission of %s message
Line 1079: ...for transmission of a non-GMM message
Line 1085: ERROR: Table is already full...
Line 1112: PduId %04X confirmed as entry %d in SAPI-1 Tx table
Line 1122: ERROR: PduId %04X does NOT match appropriate table entry...
Line 1128: ERROR: PduId submitted for confirmation has the value NOT_SAPI1_PDU...
Line 1151: Checking SAPI-1 Tx table for PduId match...
Line 1155: PduId 0x%04X matched...
Line 1165: ...corresponding to %s
Line 1169: ...corresponding to a non-GMM SAPI-1 PDU
Line 1174: ERROR: PduId 0x%04X does not match that of first active entry...
Line 1180: PduId 0x%04X matched...
Line 1189: ...corresponding to %s
Line 1194: ...corresponding to a non-GMM SAPI-1 PDU
Line 1202: PduId -> NOT_SAPI1_PDU
Line 1223: First active entry removed from the SAPI-1 Tx table...
Line 1235: PduId %04X does not match first active entry in the SAPI-1 Tx table...
Line 1241:  active entry matched in  the SAPI-1 Tx table at %d
Line 1298: %s currently occupies position %d in the SAPI-1 Tx table...
Line 1323: Flushing the following %d active entries from the SAPI-1 submit table...
Line 1325: -------------
Line 1341: No active entries to flush from the SAPI-1 submit table...
Line 1355: Entry number %d corresponds to PduId = %04X
Line 1359:  ==> GMM PDU
Line 1360:  ==> %s
Line 1364:  ==> Non-GMM PDU
Line 1367: -------------
Line 1379: mm_AssignNewTlli:
Line 1422: mm_AssignNewAndOldTlli:
Line 1439: mm_OldTlliType = %s, mm_TlliOld = %02X %02X %02X %02X
Line 1443: mm_CurrentTlliType = %s, mm_Tlli = %02X %02X %02X %02X
Line 1456: mm_UnassignTlli:
Line 1607: ERROR: ReqdTlliType is not GMM_LOCAL_TLLI or GMM_FOREIGN_TLLI...
Line 1615: TLLI change reqd for RAU procedure as P-TMSI has changed since previous TLLI assignment to LLC...
Line 1627: TLLI assignment/change reqd for RAU procedure as TLLI assigned to LLC not of reqd type...
Line 1653: mm_DecodeLlGmmUnitDataIndMsg:
Line 1669: 
Line 1717: Invalid SMS Protocol Discriminator. No SMS Msg in GSM / GPRS to GMM !
Line 1725: Invalid ProtocolDisc (0x%x) in mm_DecodeLlGmmUnitDataIndMsg
Line 1738: No action required in this State in mm_DecodeLlGmmUnitDataIndMsg
Line 1746: Invalid mm_GmmState in mm_DecodeLlGmmUnitDataIndMsg
Line 1817: GS31(SM/SMS/SS): ucTransactionID = 0x%02X, ucProtocol =%s, ucSendSeqNum =0x%02X
Line 1818: GS31(SM/SMS/SS): ucMessageType =0x%02X, ucChannel =0x%02X
Line 1819: GS31(SM/SMS/SS): Raw data length =%d
Line 1834: 
Line 1836: Cipher = %s
Line 1838: PduId = 0x%04X
Line 1904: 
Line 1957: LLC requested to suspend....
Line 1965: LLC is already suspended....
Line 2005: LLC Resumption is avoided as current Operating mode is MM_MOBILE_CLASS_C_CS
Line 2014: LLC requested to resume....
Line 2027: Cant Resume LLC At this Time Ignored
Line 2032: LLC is not suspended....
Line 2090: 
Line 2277: ERROR: Invalid NewTlliType in mm_SetNewTlli....
Line 2333: mm_Tlli = %02X %02X %02X %02X
Line 2351: mm_TlliOld = %02X %02X %02X %02X
Line 2364: mm_CurrentTlliType = %s
Line 2377: mm_OldTlliType = %s
Line 2413: Cause -> %s
Line 2469: IsCrcFailure -> %d
