Line 102: GTimeSetTcuFrameCnt : tcu(%d) gcnt(%d)
Line 108: Adjusted Irat fn (%d)
Line 250: [GTimeSub] Prev FN(%d) TO(%d) / CUR FN(%d) TO(%d)
Line 299: [GTimeCmp] Prev FN(%d) TO(%d) / CUR FN(%d) TO(%d)
Line 325: [GTimeCmp] Diff FN (%d) TO (%d) Result (%d)
