Line 170: [VHM]not defined codec type(%d)
Line 180: [VHM]StartMainVoiceLoop(%d)
Line 270: [VHM]amr_VoiceFwInit LoopbackDelay(%d), hLBVocBypassFlag(%d)
Line 287: [VHM]VoiceFwInit(amrMode:%d,Codec:%d,FSMode:%d,LBMode:%d)
Line 311: [VHM]amr_VoiceFwEnd LoopbackDelay(%d), hLBVocBypassFlag(%d)
Line 399: [VHM]Enc Start(%d) : codecMode(%d), evrcPktMode(%d)
Line 465: [VHM]Dec Start(%d) : decFlag(%d),codecMode(%d),rxFrmType(%d),txFrmType(%d)
Line 536: [VHM]vhm_PreprocChCreation Start(%d)
Line 558: [VHM]VoiceFWEnd Start(%d)
Line 649: CPmain_EncodeVoice :isEncReq(%d)
Line 651: CPmain_EncodeVoice :isTxSEDone(%d)
Line 669: [VHM]not ready to proc DEC(%d,%d)
Line 732: [VHM]EncDone(%d) : txFrmType(%d),vbrCodecMode(%d),sid(%d)
Line 789: [VHM]vhm_EncDoneEvt hLBVocBypassFlag(%d) LoopbackDelay(%d)
Line 801: [VHM]EncDone : Undefined FRAME_SYNC_MODE(%d) !!!
Line 838: [VHM]DecDone(%d) : evsCoreMode(%d), frmSyncMode(%d)
