Line 99: [IRAT U2L] uphy_CEutraMeasureStepFsm_step: EARFCN (%d), numOfEutraCells (%d), AGC1 (%d), AGC2 (%d), AFC (%d)
Line 99: [IRAT U2L] uphy_CEutraMeasureStepFsm_step: EARFCN (%d), numOfEutraCells (%d), AGC1 (%d), AGC2 (%d), AFC (%d)
Line 112: [IRAT U2L] uphy_CEutraMeasureStepFsm_step: cellId=%d, start (sfn, tti, offset)=(%d, %d, %d), duration (sfn, tti, offset)=(%d, %d, %d)
Line 112: [IRAT U2L] uphy_CEutraMeasureStepFsm_step: cellId=%d, start (sfn, tti, offset)=(%d, %d, %d), duration (sfn, tti, offset)=(%d, %d, %d)
Line 185: S0  ### Critical Error UmtsMessagePtr mMsg = NULL (%d)
Line 185: S0  ### Critical Error UmtsMessagePtr mMsg = NULL (%d)
Line 251: [IRAT U2L] uphy_CEutraMeasureStepFsm_processReplyInfo: numOfEutraCells (%d), EARFCN (%d), cellId (%d), cyType (%d), framePosition (%d), RSRP (%d), RSRQ (%d)
Line 251: [IRAT U2L] uphy_CEutraMeasureStepFsm_processReplyInfo: numOfEutraCells (%d), EARFCN (%d), cellId (%d), cyType (%d), framePosition (%d), RSRP (%d), RSRQ (%d)
Line 258: S0  ### Critical Error eutraCellMeasResultsList = NULL (%d)
Line 258: S0  ### Critical Error eutraCellMeasResultsList = NULL (%d)
Line 268: [IRAT U2L] uphy_CEutraMeasureStepFsm_processReplyInfo: AGC1 (%d), AGC2 (%d), AFC (%d)
Line 268: [IRAT U2L] uphy_CEutraMeasureStepFsm_processReplyInfo: AGC1 (%d), AGC2 (%d), AFC (%d)
