Line 103: [IRAT U2L] uphy_CEutraCellSearchStepFsm_step: EARFCN (%d), start (sfn, tti, offset)=(%d, %d, %d), duration (sfn, tti, offset)=(%d, %d, %d)
Line 103: [IRAT U2L] uphy_CEutraCellSearchStepFsm_step: EARFCN (%d), start (sfn, tti, offset)=(%d, %d, %d), duration (sfn, tti, offset)=(%d, %d, %d)
Line 107: [IRAT U2L] uphy_CEutraCellSearchStepFsm_step: EARFCN (%d), AGC1 (%d), AGC2 (%d), AFC (%d)
Line 107: [IRAT U2L] uphy_CEutraCellSearchStepFsm_step: EARFCN (%d), AGC1 (%d), AGC2 (%d), AFC (%d)
Line 181: S0  ### Critical Error UmtsMessagePtr mMsg  = NULL (%d)
Line 181: S0  ### Critical Error UmtsMessagePtr mMsg  = NULL (%d)
Line 248: [IRAT U2L] uphy_CEutraCellSearchStepFsm_processReplyInfo: numOfEutraCells (%d), EARFCN (%d), cellId (%d), cyType (%d), framePosition (%d)
Line 248: [IRAT U2L] uphy_CEutraCellSearchStepFsm_processReplyInfo: numOfEutraCells (%d), EARFCN (%d), cellId (%d), cyType (%d), framePosition (%d)
Line 255: S0  ### Critical Error eutraCellSearchResultsList  = NULL (%d)
Line 255: S0  ### Critical Error eutraCellSearchResultsList  = NULL (%d)
Line 267: [IRAT U2L] uphy_CEutraCellSearchStepFsm_processReplyInfo: AGC1 (%d), AGC2 (%d), AFC (%d)
Line 267: [IRAT U2L] uphy_CEutraCellSearchStepFsm_processReplyInfo: AGC1 (%d), AGC2 (%d), AFC (%d)
