Line 96: ###[NR_WAKEUP_DEV] DevWakeupNr::InitSleep: MifWakeUpTime(%d)
Line 141: ###[WARNING][NR_WAKEUP_DEV] DevWakeupNr::EnableDrxIntr: Unexpected Intr(%d)
Line 145: ###[NR_WAKEUP_DEV] DevWakeupNr::EnableDrxIntr: Intr(%d)
Line 198: ###[WARNING][NR_WAKEUP_DEV] DevWakeupNr::DisableDrxIntr: Unexpected Intr(%d)
Line 202: ###[NR_WAKEUP_DEV] DevWakeupNr::DisableDrxIntr: Intr(%d), Pend(%d)
Line 242: ###[WARNING][NR_WAKEUP_DEV] DevWakeupNr::ClearDrxIntr: Unexpected Intr(%d)
Line 246: ###[NR_WAKEUP_DEV] DevWakeupNr::ClearDrxIntr: Intr(%d)
Line 362: ###[NR_WAKEUP_DEV] ForceSwSysValidEnable: ReqSleep(%d), Status(0x%X), XfrRefCnt(0x%x)
Line 389: ###[NR_WAKEUP_DEV] AbortSleep: ReqSleep(%d), Status(0x%X), SlpCnt(%d), Remained Time(%d)
Line 409: ###[NR_WAKEUP_DEV] StartSleep: SleepTime(%d)
Line 427: ###[NR_WAKEUP_DEV] SetOvrRcValue: OvrRcValue(%d), RefCnt(Ini: %d, Gat: %d)
Line 454: ###[NR_WAKEUP_DEV] SetFreqErrAccPeriod: Enable(%d), Period(%d)
Line 605: ###[NR_WAKEUP_DEV] TimingCompensation: SleepMclk(%d), SleepSclk(%d), SceTotalModemClk(0x%x), sleepTime(SFN %d, SubFrame %d, Offset %d), WakeupStrOffset(%d)
Line 608: ###[NR_WAKEUP_DEV] TimingCompensation: TotalSleepMclkCnt(%d), DrxStart_Ref_Cnt(0x%x), Xfr_ref_cnt(0x%x), SlpStart_Ref_Rtg(%d), SlpXfr_Ref_rtg(%d)
Line 637: ###[NR_WAKEUP_DEV] RtgDiffBefSleep(%d) RtfDiffAftSleep(%d) RtgAlign(%d)
Line 664: ###[NR_WAKEUP_DEV] WakeupSfnUpdate: CurrTti(%d), CurrOffset(%d)
Line 726: ##[NR_WAKEUP] WakeupSfnCompensation: CompensatedRtg(SFN %d SubFrame %d Offset %d), SleepStartRtg(SFN %d SubFrame %d Offset %d), PaltimeDiff(%d us)
