Line 55: [error] NrTx_Isr1: wrong cc idx (%d)
Line 87: [error] NrTx_Isr1: wrong cc idx (%d)
Line 114: [error] NrTx_Isr1: wrong cc idx (%d)
Line 144: [error] NrTxMod_Isr1: wrong cc idx (%d)
Line 161: [error] NrTxMod_Isr2: wrong cc idx (%d)
