Line 110: Uhal Stops PCCPCH Phych %d (type=%d, RlsStr=%x)
Line 113: Uhal Stops SCCPCH Phych %d (type=%d, RlsStr=%x)
Line 116: Uhal Stops DL DPCH Phych %d (type=%d, RlsStr=%x)
Line 119: Uhal Stops PICH Phych %d (type=%d, RlsStr=%x)
Line 122: Uhal Stops AICH Phych %d (type=%d, RlsStr=%x)
Line 125: Uhal Stops MICH Phych %d (type=%d, RlsStr=%x)
Line 128: Uhal Stops SCCPCH_MBMS_RL0 Phych %d (type=%d, RlsStr=%x)
Line 131: Uhal Stops SCCPCH_MBMS_RL1 Phych %d (type=%d, RlsStr=%x)
Line 134: Uhal Stops SCCPCH_MBMS_RL2 Phych %d (type=%d, RlsStr=%x)
Line 137: Uhal Stops SCCPCH(0) for CBS Phych %d (type=%d, RlsStr=%x)
Line 140: Uhal Stops SCCPCH(1) for CBS Phych %d (type=%d, RlsStr=%x)
Line 143: Uhal Stops SCCPCH(2) for CBS Phych %d (type=%d, RlsStr=%x)
Line 146: Uhal Stops ??? Phych %d (type=%d, RlsStr=%x)
Line 208: activeStackId %d PhychType = %d
